import React, { createContext, useState, useContext, useCallback, ReactNode } from 'react';
export type UserLanguage = 'fr' | 'en' | 'es' | 'ar' | 'zh' | 'pt' | 'de';

interface LanguageContextType {
  language: UserLanguage;
  currentLanguage: UserLanguage;
  setLanguage: (lang: UserLanguage) => void;
  changeLanguage: (lang: UserLanguage) => void;
  t: (key: string, params?: Record<string, any>) => string;
  getLanguageName: (lang: UserLanguage) => string;
  availableLanguages: UserLanguage[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<UserLanguage, Record<string, string>> = {
  fr: {
    "footer.company": "Chine ton usine",
    "footer.about": "À propos",
    "footer.careers": "Carrières",
    "footer.news": "Actualités",
    "footer.solutions": "Solutions",
    "footer.sourcing": "Sourcing",
    "footer.quality": "Qualité",
    "footer.logistics": "Logistique",
    "footer.resources": "Ressources",
    "footer.help": "Centre d'aide",
    "footer.blog": "Blog",
    "footer.guides": "Guides",
    "footer.legal": "Légal",
    "footer.privacy": "Confidentialité",
    "footer.terms": "Conditions",
    "footer.cookies": "Cookies",
    "footer.contact": "Contact",
    "footer.contactus": "Nous contacter",
    "footer.email": "Email",
    "footer.phone": "Téléphone",
    "footer.copyright": "Chine ton usine",
    "footer.rights": "Tous droits réservés",
    "home": "Accueil",
    "search": "Rechercher",
    "search.placeholder": "Rechercher des produits...",
    "dashboard": "Tableau de bord",
    "logout": "Déconnexion",
    "discover": "Découvrir",

    // Authentication
    "email": "Email",
    "password": "Mot de passe",
    "confirmPassword": "Confirmer le mot de passe",
    "login": "Connexion",
    "register": "Inscription",
    "loginDescription": "Connectez-vous pour accéder à votre compte",
    "accountType": "Type de compte",
    "role.customer": "Client",
    "role.supplier": "Fournisseur",
    "role.sourcer": "Sourceur",
    "role.influencer": "Influenceur",

    // SupplierProfile Page translations
    "supplier.loadingProfile": "Chargement du profil...",
    "supplier.goldSupplier": "Fournisseur Gold",
    "supplier.reviews": "avis",
    "supplier.since": "Depuis",
    "supplier.contact": "Contact",
    "supplier.viewProducts": "Voir les Produits",
    "supplier.overview": "Aperçu",
    "supplier.products": "Produits",
    "supplier.businessCards": "Cartes de Visite",
    "supplier.certifications": "Certifications",
    "supplier.gallery": "Galerie",
    "supplier.aboutCompany": "À Propos de l'Entreprise",
    "supplier.specialties": "Spécialités",
    "supplier.performance": "Performance",
    "supplier.ordersCompleted": "Commandes Complétées",
    "supplier.responseTime": "Temps de Réponse",
    "supplier.onTimeDelivery": "Livraison à Temps",
    "supplier.viewAll": "Voir Tout",
    "supplier.myBusinessCards": "Mes Cartes de Visite",
    "supplier.createBusinessCardsDesc": "Créez et personnalisez vos cartes de visite professionnelles. Partagez-les facilement avec vos clients et partenaires.",
    "supplier.viewBusinessCardsDesc": "Découvrez les cartes de visite de ce fournisseur et téléchargez-les pour vos contacts.",
    "supplier.businessCardsAvailable": "Cartes de Visite Disponibles",
    "supplier.supplierSharesCards": "Ce fournisseur partage ses cartes de visite avec les partenaires.",
    "supplier.certificationsAndStandards": "Certifications et Normes",
    "supplier.validCertification": "Certification Valide",
    "supplier.companyGallery": "Galerie de l'Entreprise",
    "supplier.customerReviews": "Avis Clients",
    "supplier.weeksAgo": "il y a {{count}} semaine{{count, plural, one {} other {s}}}",
    "supplier.sampleReviewText": "Excellent fournisseur ! Qualité de produit impeccable et livraison très rapide. Je recommande vivement.",
    "supplier.helpful": "Utile",
    "supplier.reply": "Répondre",
    "supplier.contactInfo": "Informations de Contact",
    "supplier.address": "Adresse",
    "supplier.phone": "Téléphone",
    "supplier.email": "Email",
    "supplier.website": "Site Web",
    "supplier.companyInfo": "Informations sur l'Entreprise",
    "supplier.foundedIn": "Fondée en",
    "supplier.employees": "Employés",
    "supplier.quickActions": "Actions Rapides",
    "supplier.sendMessage": "Envoyer un Message",
    "supplier.requestQuote": "Demander un Devis",
    "supplier.downloadCatalog": "Télécharger le Catalogue",

    // Common
    "units": "unités",
    "cbm": "CBM",
    "cancel": "Annuler",
    "confirm": "Confirmer",
    "close": "Fermer",

    // UserProfile translations
    "userProfile.title": "Mon Profil",
    "userProfile.loading": "Chargement du profil...",
    "userProfile.mustBeLoggedIn": "Vous devez être connecté pour voir votre profil.",
    "userProfile.editProfile": "Modifier le profil",
    "userProfile.saveChanges": "Sauvegarder",
    "userProfile.cancelEdit": "Annuler",
    "userProfile.changePhoto": "Changer la photo",
    "userProfile.uploadingPhoto": "Téléchargement...",
    "userProfile.photoUploadSuccess": "Photo de profil mise à jour avec succès !",
    "userProfile.photoUploadError": "Erreur lors du téléchargement de la photo",
    "userProfile.fileTooLarge": "Le fichier est trop volumineux (max 5MB)",
    "userProfile.invalidFileType": "Veuillez sélectionner une image valide",
    "userProfile.profileUpdateSuccess": "Profil mis à jour avec succès !",
    "userProfile.profileUpdateError": "Erreur lors de la sauvegarde du profil",
    "userProfile.personalInfo": "Informations personnelles",
    "userProfile.contactInfo": "Informations de contact",
    "userProfile.preferences": "Préférences",
    "userProfile.security": "Sécurité",
    "userProfile.activity": "Activité récente",
    "userProfile.notifications": "Notifications",
    "userProfile.privacy": "Confidentialité",
    "userProfile.name": "Nom",
    "userProfile.firstName": "Prénom",
    "userProfile.lastName": "Nom de famille",
    "userProfile.phone": "Téléphone",
    "userProfile.address": "Adresse",
    "userProfile.city": "Ville",
    "userProfile.country": "Pays",
    "userProfile.postalCode": "Code postal",
    "userProfile.dateOfBirth": "Date de naissance",
    "userProfile.gender": "Genre",
    "userProfile.male": "Homme",
    "userProfile.female": "Femme",
    "userProfile.other": "Autre",
    "userProfile.changePassword": "Changer le mot de passe",
    "userProfile.currentPassword": "Mot de passe actuel",
    "userProfile.newPassword": "Nouveau mot de passe",
    "userProfile.confirmNewPassword": "Confirmer le nouveau mot de passe",
    "userProfile.showPassword": "Afficher le mot de passe",
    "userProfile.hidePassword": "Masquer le mot de passe",
    "userProfile.twoFactorAuth": "Authentification à deux facteurs",
    "userProfile.enableTwoFactor": "Activer l'authentification à deux facteurs",
    "userProfile.disableTwoFactor": "Désactiver l'authentification à deux facteurs",
    "userProfile.emailNotifications": "Notifications par email",
    "userProfile.pushNotifications": "Notifications push",
    "userProfile.profileChanges": "Changements de profil",
    "userProfile.marketingEmails": "Emails marketing",
    "userProfile.publicProfile": "Profil public",
    "userProfile.profileVisibility": "Votre profil est visible par les autres utilisateurs",
    "userProfile.profilePrivate": "Rendre le profil privé",
    "userProfile.deleteAccount": "Supprimer le compte",
    "userProfile.deleteAccountWarning": "Cette action est irréversible",
    "userProfile.favoriteProducts": "Produits favoris",
    "userProfile.recentOrders": "Commandes récentes",
    "userProfile.accountCreated": "Compte créé",
    "userProfile.lastLogin": "Dernière connexion",
    "userProfile.accountStats": "Statistiques du compte",
    "userProfile.totalOrders": "Commandes totales",
    "userProfile.totalSpent": "Total dépensé",
    "userProfile.memberSince": "Membre depuis",
    "userProfile.loyaltyPoints": "Points de fidélité",

    // Dashboard translations  
    "dashboard.welcome": "Bienvenue",
    "dashboard.overview": "Aperçu",
    "dashboard.recentActivity": "Activité récente",
    "dashboard.quickActions": "Actions rapides",
    "dashboard.statistics": "Statistiques",
    "dashboard.notifications": "Notifications",
    "dashboard.settings": "Paramètres",

    // Navigation
    "nav.home": "Accueil",
    "nav.products": "Produits",
    "nav.discover": "Découvrir",
    "nav.dashboard": "Tableau de bord",
    "nav.profile": "Profil",
    "nav.settings": "Paramètres",
    "nav.help": "Aide",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "nav.logout": "Déconnexion",
    "nav.login": "Connexion",
    "myProfile": "Mon profil",
    "mySupplierProfile": "Mon profil fournisseur",

    // Homepage translations
    "homepage.title": "Chine ton usine",
    "homepage.subtitle": "ÇA VA VOUS",
    "homepage.subtitle.highlight": "PLAIRE",
    "homepage.tagline": "Coup de foudre inévitable.",
    "homepage.search.placeholder": "Recherchez un produit, une marque...",
    "homepage.hero.title": "Trouvez votre usine en Chine",
    "homepage.hero.subtitle": "Connectez-vous directement avec des fabricants vérifiés",
    "homepage.hero.cta": "Commencer maintenant",

    // Homepage categories
    "homepage.categories.home": "Accueil",
    "homepage.categories.electronics": "Électronique",
    "homepage.categories.fashion": "Mode",
    "homepage.categories.home.category": "Maison",
    "homepage.categories.beauty": "Beauté",
    "homepage.categories.sports": "Sports",
    "homepage.categories.automotive": "Automobile",
    "homepage.categories.tools": "Outils",
    "homepage.categories.machinery": "Machinerie",
    "homepage.categories.toys": "Jouets",
    "homepage.categories.books": "Livres",
    "homepage.categories.music": "Musique",
    "homepage.categories.garden": "Jardin",

    // Homepage cards
    "homepage.cards.technology": "Technologie",
    "homepage.cards.electronics": "Électronique",
    "homepage.cards.electronics.description": "Découvrez les dernières innovations électroniques",
    "homepage.cards.explore": "Explorer",
    "homepage.cards.fashion.title": "Mode",
    "homepage.cards.textile": "Textile",
    "homepage.cards.textile.description": "Des tissus de qualité pour tous vos besoins",
    "homepage.cards.industrial": "Industriel",
    "homepage.cards.machinery": "Machinerie",
    "homepage.cards.machinery.description": "Équipements industriels de haute qualité",
    "homepage.cards.new": "Nouveau",
    "homepage.cards.decoration": "Décoration",
    "homepage.cards.home.garden": "Maison & Jardin",
    "homepage.cards.home.garden.description": "Transformez votre espace de vie",
    "homepage.cards.educational": "Éducatif",
    "homepage.cards.toys.children": "Jouets & Enfants",
    "homepage.cards.toys.description": "Des jouets sûrs et éducatifs pour les enfants",
    "homepage.cards.parts": "Pièces",

    // Homepage stats
    "homepage.stats.products": "Produits",
    "homepage.stats.suppliers": "Fournisseurs",
    "homepage.stats.satisfaction": "Satisfaction",
    "homepage.stats.response": "Réponse",
    "homepage.categories.popular": "Catégories Populaires",
    "homepage.categories.popular.subtitle": "Découvrez nos catégories les plus demandées",
    "homepage.search.placeholder.dev": "🚧 Nouvelle interface en cours de développement...",
    "homepage.cards.auto.moto": "Auto & Moto",
    "homepage.cards.auto.description": "Pièces et accessoires automobiles",

    // Homepage sections
    "homepage.categories.section.title": "Explorez par catégorie",
    "homepage.categories.section.subtitle": "Trouvez rapidement ce que vous cherchez",
    "homepage.recommendations.loading": "Chargement des recommandations...",
    "homepage.recommendations.badge": "Tendances",
    "homepage.recommendations.title": "Recommandé pour vous",
    "homepage.recommendations.subtitle": "Découvrez nos sélections personnalisées",
    "homepage.recommendations.viewAll": "Voir tout",
    "homepage.recommendations.discover": "Découvrir",
    "homepage.cta.title": "Ça va vous",
    "homepage.cta.highlight": "PLAIRE",
    "homepage.cta.subtitle": "Coup de foudre inévitable.",
    "homepage.cta.button": "Découvrir nos produits",

    // Sourcer Dashboard
    "sourcer.dashboard.title": "Tableau de Bord Sourceur",
    "sourcer.dashboard.description": "Interface de gestion pour les sourceurs.",
    "sourcer.dashboard.comingSoon": "Fonctionnalité à venir",

    // Homepage benefits
    "homepage.benefits.delivery.title": "Livraison Rapide",
    "homepage.benefits.delivery.description": "Expédition sous 24-48h partout en France",
    "homepage.benefits.payment.title": "Paiement Sécurisé",
    "homepage.benefits.payment.description": "Transactions protégées et garanties",
    "homepage.benefits.support.title": "Support 24/7",
    "homepage.benefits.support.description": "Une équipe dédiée à votre service",

    // Homepage how it works
    "homepage.how.title": "Comment ça marche ?",
    "homepage.how.subtitle": "Trois étapes simples pour commander depuis la Chine",
    "homepage.how.step1.title": "1. Recherchez",
    "homepage.how.step1.description": "Trouvez le produit parfait parmi des milliers de références",
    "homepage.how.step2.title": "2. Contactez",
    "homepage.how.step2.description": "Échangez directement avec les fournisseurs vérifiés",
    "homepage.how.step3.title": "3. Commandez",
    "homepage.how.step3.description": "Finalisez votre achat en toute sécurité",
    "homepage.how.cta": "Commencer maintenant",

    // Homepage optimization
    "homepage.optimize.title": "Optimisez vos commandes",
    "homepage.optimize.search.title": "Recherchez des offres",
    "homepage.optimize.search.description": "Parcourez des milliers de produits et trouvez les meilleures offres",
    "homepage.optimize.identify.title": "Identifiez le bon fournisseur",
    "homepage.optimize.identify.description": "Comparez les fournisseurs et choisissez le meilleur pour vos besoins",
    "homepage.optimize.pay.title": "Payez en toute confiance",
    "homepage.optimize.pay.description": "Transactions sécurisées avec protection acheteur",
    "homepage.optimize.manage.title": "Gérez facilement",
    "homepage.optimize.manage.description": "Suivez vos commandes et gérez vos relations fournisseurs",

    // Homepage discover
    "homepage.discover.network": "Réseau global",
    "homepage.discover.title": "Découvrez tous nos fournisseurs",
    "homepage.discover.highlight": "vérifiés",
    "homepage.discover.subtitle": "Connectez-vous avec plus de 1000 fournisseurs vérifiés dans le monde entier",
    "homepage.discover.button": "Explorer les fournisseurs",
    "homepage.discover.verified": "Plus de 1000 fournisseurs vérifiés",

    // Homepage process
    "homepage.process.title": "Notre processus simplifié",
    "homepage.process.subtitle": "De la recherche à la livraison, nous vous accompagnons à chaque étape",
    "homepage.process.step1.title": "Recherche",
    "homepage.process.step1.description": "Trouvez vos produits",
    "homepage.process.step2.title": "Contact",
    "homepage.process.step2.description": "Échangez avec les fournisseurs",
    "homepage.process.step3.title": "Commande",
    "homepage.process.step3.description": "Passez votre commande",
    "homepage.process.step4.title": "Paiement",
    "homepage.process.step4.description": "Payez en sécurité",
    "homepage.process.cta": "Démarrer maintenant",

    // Homepage final CTA
    "homepage.final.title": "Prêt à commencer ?",
    "homepage.final.subtitle": "Rejoignez des milliers d'entreprises qui font confiance à notre plateforme",
    "homepage.final.button": "Créer mon compte",

    // Container translations
    "containers": "Conteneurs",
    "containers.title": "Liste des conteneurs",
    "containers.loading": "Chargement des conteneurs...",
    "containers.error": "Erreur de chargement",
    "containers.name": "Nom du conteneur",
    "containers.departure": "Lieu de départ",
    "containers.arrival": "Lieu d'arrivée",
    "containers.estimatedDeparture": "Date de départ estimée",
    "containers.status": "Statut",
    "containers.status.active": "Actif",
    "containers.status.closed": "Clôturé",
    "containers.capacity": "Capacité",
    "containers.usedCapacity": "Capacité utilisée",
    "containers.availableCapacity": "Capacité disponible",
    "containers.totalCapacity": "Capacité totale",
    "containers.closedMessage": "Ce conteneur est clôturé et n'est plus réservable.",
    "containers.almostFullMessage": "Ce conteneur est presque plein, réservez vite !",
    "containers.availableMessage": "Ce conteneur est disponible pour de nouvelles réservations.",
    "preorder.success": "Précommande créée avec succès !",
    "preorder.button": "Précommander",

    // Forms
    "form.save": "Sauvegarder",
    "form.cancel": "Annuler",
    "form.submit": "Soumettre",
    "form.reset": "Réinitialiser",
    "form.required": "Requis",
    "form.optional": "Optionnel",
    "form.loading": "Chargement...",
    "form.saving": "Sauvegarde...",
    "form.saved": "Sauvegardé",
    "form.error": "Erreur",
    "form.success": "Succès",

    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAsRead": "Marquer comme lu",
    "notifications.markAllAsRead": "Tout marquer comme lu",
    "notifications.noNotifications": "Aucune notification",
    "notifications.new": "Nouveau",
    "notifications.settings": "Paramètres de notification",

    // Errors
    "error.generic": "Une erreur s'est produite",
    "error.network": "Erreur de réseau",
    "error.notFound": "Page non trouvée",
    "error.unauthorized": "Non autorisé",
    "error.forbidden": "Accès interdit",
    "error.serverError": "Erreur serveur",
    "error.retry": "Réessayer",
    "error.goHome": "Retour à l'accueil",

    // Loading states
    "loading": "Chargement...",
    "loading.products": "Chargement des produits...",
    "loading.user": "Chargement de l'utilisateur...",
    "loading.data": "Chargement des données...",

    // Actions
    "action.edit": "Modifier",
    "action.delete": "Supprimer",
    "action.view": "Voir",
    "action.download": "Télécharger",
    "action.upload": "Téléverser",
    "action.share": "Partager",
    "action.copy": "Copier",
    "action.print": "Imprimer",
    "action.export": "Exporter",
    "action.import": "Importer",

    // Time
    "time.now": "Maintenant",
    "time.today": "Aujourd'hui",
    "time.yesterday": "Hier",
    "time.tomorrow": "Demain",
    "time.thisWeek": "Cette semaine",
    "time.lastWeek": "La semaine dernière",
    "time.thisMonth": "Ce mois",
    "time.lastMonth": "Le mois dernier",
    "time.thisYear": "Cette année",
    "time.lastYear": "L'année dernière",

    // Status
    "status.active": "Actif",
    "status.inactive": "Inactif",
    "status.pending": "En attente",
    "status.approved": "Approuvé",
    "status.rejected": "Rejeté",
    "status.completed": "Terminé",
    "status.cancelled": "Annulé",
    "status.draft": "Brouillon",
    "status.published": "Publié",

    // --- AJOUT DES CLÉS MANQUANTES POUR LA PAGE D'ACCUEIL DANS TOUTES LES LANGUES ---
    // Pour chaque bloc de langue (fr, en, es, ar, zh, pt, de), je complète les clés manquantes de la page d'accueil
    // Les valeurs sont traduites ou, à défaut, un placeholder est utilisé

    // Exemple pour le bloc espagnol (à placer dans le bloc 'es')
    "homepage.title": "Por traducir",
    "homepage.subtitle": "Por traducir",
    "homepage.subtitle.highlight": "Por traducir",
    "homepage.tagline": "Por traducir",
    "homepage.hero.title": "Por traducir",
    "homepage.hero.subtitle": "Por traducir",
    "homepage.hero.cta": "Por traducir",
    "homepage.cta.title": "Por traducir",
    "homepage.cta.highlight": "Por traducir",
    "homepage.cta.subtitle": "Por traducir",
    "homepage.cta.button": "Por traducir",
    "homepage.final.title": "Por traducir",
    "homepage.final.subtitle": "Por traducir",
    "homepage.final.button": "Por traducir"
  },

  en: {
    "footer.company": "Chine ton usine",
    "footer.about": "About",
    "footer.careers": "Careers",
    "footer.news": "News",
    "footer.solutions": "Solutions",
    "footer.sourcing": "Sourcing",
    "footer.quality": "Quality",
    "footer.logistics": "Logistics",
    "footer.resources": "Resources",
    "footer.help": "Help Center",
    "footer.blog": "Blog",
    "footer.guides": "Guides",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cookies": "Cookies",
    "footer.contact": "Contact",
    "footer.contactus": "Contact us",
    "footer.email": "Email",
    "footer.phone": "Phone",
    "footer.copyright": "Chine ton usine",
    "footer.rights": "All rights reserved",
    "home": "Home",
    "search": "Search",
    "search.placeholder": "Search for products...",
    "dashboard": "Dashboard",
    "logout": "Logout",
    "discover": "Discover",

    // Authentication
    "email": "Email",
    "password": "Password",
    "confirmPassword": "Confirm Password",
    "login": "Login",
    "register": "Register",
    "loginDescription": "Sign in to access your account",
    "accountType": "Account Type",
    "role.customer": "Customer",
    "role.supplier": "Supplier",
    "role.sourcer": "Sourcer",
    "role.influencer": "Influencer",

    // SupplierProfile Page translations
    "supplier.loadingProfile": "Loading profile...",
    "supplier.goldSupplier": "Gold Supplier",
    "supplier.reviews": "reviews",
    "supplier.since": "Since",
    "supplier.contact": "Contact",
    "supplier.viewProducts": "View Products",
    "supplier.overview": "Overview",
    "supplier.products": "Products",
    "supplier.businessCards": "Business Cards",
    "supplier.certifications": "Certifications",
    "supplier.gallery": "Gallery",
    "supplier.aboutCompany": "About the Company",
    "supplier.specialties": "Specialties",
    "supplier.performance": "Performance",
    "supplier.ordersCompleted": "Orders Completed",
    "supplier.responseTime": "Response Time",
    "supplier.onTimeDelivery": "On-Time Delivery",
    "supplier.viewAll": "View All",
    "supplier.myBusinessCards": "My Business Cards",
    "supplier.createBusinessCardsDesc": "Create and customize your professional business cards. Share them easily with your clients and partners.",
    "supplier.viewBusinessCardsDesc": "Discover this supplier's business cards and download them for your contacts.",
    "supplier.businessCardsAvailable": "Business Cards Available",
    "supplier.supplierSharesCards": "This supplier shares their business cards with partners.",
    "supplier.certificationsAndStandards": "Certifications and Standards",
    "supplier.validCertification": "Valid Certification",
    "supplier.companyGallery": "Company Gallery",
    "supplier.customerReviews": "Customer Reviews",
    "supplier.weeksAgo": "{{count}} week{{count, plural, one {} other {s}}} ago",
    "supplier.sampleReviewText": "Excellent supplier! Impeccable product quality and very fast delivery. I highly recommend.",
    "supplier.helpful": "Helpful",
    "supplier.reply": "Reply",
    "supplier.contactInfo": "Contact Information",
    "supplier.address": "Address",
    "supplier.phone": "Phone",
    "supplier.email": "Email",
    "supplier.website": "Website",
    "supplier.companyInfo": "Company Information",
    "supplier.foundedIn": "Founded in",
    "supplier.employees": "Employees",
    "supplier.quickActions": "Quick Actions",
    "supplier.sendMessage": "Send Message",
    "supplier.requestQuote": "Request Quote",
    "supplier.downloadCatalog": "Download Catalog",

    // Common
    "units": "units",
    "cbm": "CBM",
    "cancel": "Cancel",
    "confirm": "Confirm",
    "close": "Close",

    // UserProfile translations
    "userProfile.title": "My Profile",
    "userProfile.loading": "Loading profile...",
    "userProfile.mustBeLoggedIn": "You must be logged in to view your profile.",
    "userProfile.editProfile": "Edit profile",
    "userProfile.saveChanges": "Save",
    "userProfile.cancelEdit": "Cancel",
    "userProfile.changePhoto": "Change photo",
    "userProfile.uploadingPhoto": "Uploading...",
    "userProfile.photoUploadSuccess": "Profile photo updated successfully!",
    "userProfile.photoUploadError": "Error uploading photo",
    "userProfile.fileTooLarge": "File is too large (max 5MB)",
    "userProfile.invalidFileType": "Please select a valid image",
    "userProfile.profileUpdateSuccess": "Profile updated successfully!",
    "userProfile.profileUpdateError": "Error saving profile",
    "userProfile.personalInfo": "Personal information",
    "userProfile.contactInfo": "Contact information",
    "userProfile.preferences": "Preferences",
    "userProfile.security": "Security",
    "userProfile.activity": "Recent activity",
    "userProfile.notifications": "Notifications",
    "userProfile.privacy": "Privacy",
    "userProfile.name": "Name",
    "userProfile.firstName": "First name",
    "userProfile.lastName": "Last name",
    "userProfile.phone": "Phone",
    "userProfile.address": "Address",
    "userProfile.city": "City",
    "userProfile.country": "Country",
    "userProfile.postalCode": "Postal code",
    "userProfile.dateOfBirth": "Date of birth",
    "userProfile.gender": "Gender",
    "userProfile.male": "Male",
    "userProfile.female": "Female",
    "userProfile.other": "Other",
    "userProfile.changePassword": "Change password",
    "userProfile.currentPassword": "Current password",
    "userProfile.newPassword": "New password",
    "userProfile.confirmNewPassword": "Confirm new password",
    "userProfile.showPassword": "Show password",
    "userProfile.hidePassword": "Hide password",
    "userProfile.twoFactorAuth": "Two-factor authentication",
    "userProfile.enableTwoFactor": "Enable two-factor authentication",
    "userProfile.disableTwoFactor": "Disable two-factor authentication",
    "userProfile.emailNotifications": "Email notifications",
    "userProfile.pushNotifications": "Push notifications",
    "userProfile.profileChanges": "Profile changes",
    "userProfile.marketingEmails": "Marketing emails",
    "userProfile.publicProfile": "Public profile",
    "userProfile.profileVisibility": "Your profile is visible to other users",
    "userProfile.profilePrivate": "Make profile private",
    "userProfile.deleteAccount": "Delete account",
    "userProfile.deleteAccountWarning": "This action is irreversible",
    "userProfile.favoriteProducts": "Favorite products",
    "userProfile.recentOrders": "Recent orders",
    "userProfile.accountCreated": "Account created",
    "userProfile.lastLogin": "Last login",
    "userProfile.accountStats": "Account statistics",
    "userProfile.totalOrders": "Total orders",
    "userProfile.totalSpent": "Total spent",
    "userProfile.memberSince": "Member since",
    "userProfile.loyaltyPoints": "Loyalty points",

    // Dashboard translations  
    "dashboard.welcome": "Welcome",
    "dashboard.overview": "Overview",
    "dashboard.recentActivity": "Recent activity",
    "dashboard.quickActions": "Quick actions",
    "dashboard.statistics": "Statistics",
    "dashboard.notifications": "Notifications",
    "dashboard.settings": "Settings",

    // Navigation
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.discover": "Discover",
    "nav.dashboard": "Dashboard",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "nav.help": "Help",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.logout": "Logout",
    "nav.login": "Login",
    "myProfile": "My profile",
    "mySupplierProfile": "My supplier profile",

    // Homepage translations
    "homepage.title": "China Your Factory",
    "homepage.subtitle": "YOU'LL",
    "homepage.subtitle.highlight": "LOVE IT",
    "homepage.tagline": "Inevitable love at first sight.",
    "homepage.search.placeholder": "Search for a product, brand...",
    "homepage.hero.title": "Find Your Factory in China",
    "homepage.hero.subtitle": "Connect directly with verified manufacturers",
    "homepage.hero.cta": "Get Started",

    // Homepage categories
    "homepage.categories.home": "Home",
    "homepage.categories.electronics": "Electronics",
    "homepage.categories.fashion": "Fashion",
    "homepage.categories.home.category": "Home & Garden",
    "homepage.categories.beauty": "Beauty",
    "homepage.categories.sports": "Sports",
    "homepage.categories.automotive": "Automotive",
    "homepage.categories.tools": "Tools",
    "homepage.categories.machinery": "Machinery",
    "homepage.categories.toys": "Toys",
    "homepage.categories.books": "Books",
    "homepage.categories.music": "Music",
    "homepage.categories.garden": "Garden",

    // Homepage cards
    "homepage.cards.technology": "Technology",
    "homepage.cards.electronics": "Electronics",
    "homepage.cards.electronics.description": "Discover the latest electronic innovations",
    "homepage.cards.explore": "Explore",
    "homepage.cards.fashion.title": "Fashion",
    "homepage.cards.textile": "Textile",
    "homepage.cards.textile.description": "Quality fabrics for all your needs",
    "homepage.cards.industrial": "Industrial",
    "homepage.cards.machinery": "Machinery",
    "homepage.cards.machinery.description": "High-quality industrial equipment",
    "homepage.cards.new": "New",
    "homepage.cards.decoration": "Decoration",
    "homepage.cards.home.garden": "Home & Garden",
    "homepage.cards.home.garden.description": "Transform your living space",
    "homepage.cards.educational": "Educational",
    "homepage.cards.toys.children": "Toys & Children",
    "homepage.cards.toys.description": "Safe and educational toys for children",
    "homepage.cards.parts": "Parts",
    // Homepage stats
    "homepage.stats.products": "Products",
    "homepage.stats.suppliers": "Suppliers",
    "homepage.stats.satisfaction": "Satisfaction",
    "homepage.stats.response": "Response",
    "homepage.categories.popular": "Popular Categories",
    "homepage.categories.popular.subtitle": "Discover our most requested categories",
    "homepage.search.placeholder.dev": "🚧 New interface under development...",
    "homepage.cards.auto.moto": "Auto & Motorcycle",
    "homepage.cards.auto.description": "Automotive parts and accessories",

    // Homepage sections
    "homepage.categories.section.title": "Explore by category",
    "homepage.categories.section.subtitle": "Find quickly what you're looking for",
    "homepage.recommendations.loading": "Loading recommendations...",
    "homepage.recommendations.badge": "Trending",
    "homepage.recommendations.title": "Recommended for you",
    "homepage.recommendations.subtitle": "Discover our personalized selections",
    "homepage.recommendations.viewAll": "View all",
    "homepage.recommendations.discover": "Discover",
    "homepage.cta.title": "You'll",
    "homepage.cta.highlight": "LOVE IT",
    "homepage.cta.subtitle": "Inevitable love at first sight.",
    "homepage.cta.button": "Discover our products",

    // Sourcer Dashboard
    "sourcer.dashboard.title": "Sourcer Dashboard",
    "sourcer.dashboard.description": "Management interface for sourcers.",
    "sourcer.dashboard.comingSoon": "Feature coming soon",

    // Homepage benefits
    "homepage.benefits.delivery.title": "Fast Delivery",
    "homepage.benefits.delivery.description": "Shipping within 24-48h throughout France",
    "homepage.benefits.payment.title": "Secure Payment",
    "homepage.benefits.payment.description": "Protected and guaranteed transactions",
    "homepage.benefits.support.title": "24/7 Support",
    "homepage.benefits.support.description": "A dedicated team at your service",

    // Homepage how it works
    "homepage.how.title": "How it works?",
    "homepage.how.subtitle": "Three simple steps to order from China",
    "homepage.how.step1.title": "1. Search",
    "homepage.how.step1.description": "Find the perfect product among thousands of references",
    "homepage.how.step2.title": "2. Contact",
    "homepage.how.step2.description": "Exchange directly with verified suppliers",
    "homepage.how.step3.title": "3. Order",
    "homepage.how.step3.description": "Complete your purchase securely",
    "homepage.how.cta": "Get started now",

    // Homepage optimization
    "homepage.optimize.title": "Optimize your orders",
    "homepage.optimize.search.title": "Search for offers",
    "homepage.optimize.search.description": "Browse thousands of products and find the best deals",
    "homepage.optimize.identify.title": "Identify the right supplier",
    "homepage.optimize.identify.description": "Compare suppliers and choose the best for your needs",
    "homepage.optimize.pay.title": "Pay with confidence",
    "homepage.optimize.pay.description": "Secure transactions with buyer protection",
    "homepage.optimize.manage.title": "Manage easily",
    "homepage.optimize.manage.description": "Track your orders and manage your supplier relationships",

    // Homepage discover
    "homepage.discover.network": "Global network",
    "homepage.discover.title": "Discover all our suppliers",
    "homepage.discover.highlight": "verified",
    "homepage.discover.subtitle": "Connect with over 1000 verified suppliers worldwide",
    "homepage.discover.button": "Explore suppliers",
    "homepage.discover.verified": "Over 1000 verified suppliers",

    // Homepage process
    "homepage.process.title": "Our simplified process",
    "homepage.process.subtitle": "From search to delivery, we accompany you every step of the way",
    "homepage.process.step1.title": "Search",
    "homepage.process.step1.description": "Find your products",
    "homepage.process.step2.title": "Contact",
    "homepage.process.step2.description": "Exchange with suppliers",
    "homepage.process.step3.title": "Order",
    "homepage.process.step3.description": "Place your order",
    "homepage.process.step4.title": "Payment",
    "homepage.process.step4.description": "Pay securely",
    "homepage.process.cta": "Start now",

    // Homepage final CTA
    "homepage.final.title": "Ready to get started?",
    "homepage.final.subtitle": "Join thousands of companies that trust our platform",
    "homepage.final.button": "Create my account",

    // Container translations
    "containers": "Containers",
    "containers.title": "Container list",
    "containers.loading": "Loading containers...",
    "containers.error": "Loading error",
    "containers.name": "Container name",
    "containers.departure": "Departure location",
    "containers.arrival": "Arrival location",
    "containers.estimatedDeparture": "Estimated departure date",
    "containers.status": "Status",
    "containers.status.active": "Active",
    "containers.status.closed": "Closed",
    "containers.capacity": "Capacity",
    "containers.usedCapacity": "Used capacity",
    "containers.availableCapacity": "Available capacity",
    "containers.totalCapacity": "Total capacity",
    "containers.closedMessage": "This container is closed and no longer bookable.",
    "containers.almostFullMessage": "This container is almost full, book quickly!",
    "containers.availableMessage": "This container is available for new bookings.",
    "preorder.success": "Pre-order created successfully!",
    "preorder.button": "Pre-order",

    // Forms
    "form.save": "Save",
    "form.cancel": "Cancel",
    "form.submit": "Submit",
    "form.reset": "Reset",
    "form.required": "Required",
    "form.optional": "Optional",
    "form.loading": "Loading...",
    "form.saving": "Saving...",
    "form.saved": "Saved",
    "form.error": "Error",
    "form.success": "Success",

    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAsRead": "Mark as read",
    "notifications.markAllAsRead": "Mark all as read",
    "notifications.noNotifications": "No notifications",
    "notifications.new": "New",
    "notifications.settings": "Notification settings",

    // Errors
    "error.generic": "An error occurred",
    "error.network": "Network error",
    "error.notFound": "Page not found",
    "error.unauthorized": "Unauthorized",
    "error.forbidden": "Access forbidden",
    "error.serverError": "Server error",
    "error.retry": "Retry",
    "error.goHome": "Go home",

    // Loading states
    "loading": "Loading...",
    "loading.products": "Loading products...",
    "loading.user": "Loading user...",
    "loading.data": "Loading data...",

    // Actions
    "action.edit": "Edit",
    "action.delete": "Delete",
    "action.view": "View",
    "action.download": "Download",
    "action.upload": "Upload",
    "action.share": "Share",
    "action.copy": "Copy",
    "action.print": "Print",
    "action.export": "Export",
    "action.import": "Import",

    // Time
    "time.now": "Now",
    "time.today": "Today",
    "time.yesterday": "Yesterday",
    "time.tomorrow": "Tomorrow",
    "time.thisWeek": "This week",
    "time.lastWeek": "Last week",
    "time.thisMonth": "This month",
    "time.lastMonth": "Last month",
    "time.thisYear": "This year",
    "time.lastYear": "Last year",

    // Status
    "status.active": "Active",
    "status.inactive": "Inactive",
    "status.pending": "Pending",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.completed": "Completed",
    "status.cancelled": "Cancelled",
    "status.draft": "Draft",
    "status.published": "Published",

    // --- AJOUT DES CLÉS MANQUANTES POUR LA PAGE D'ACCUEIL DANS TOUTES LES LANGUES ---
    // Pour chaque bloc de langue (fr, en, es, ar, zh, pt, de), je complète les clés manquantes de la page d'accueil
    // Les valeurs sont traduites ou, à défaut, un placeholder est utilisé

    // Exemple pour le bloc espagnol (à placer dans le bloc 'es')
    "homepage.title": "Por traducir",
    "homepage.subtitle": "Por traducir",
    "homepage.subtitle.highlight": "Por traducir",
    "homepage.tagline": "Por traducir",
    "homepage.hero.title": "Por traducir",
    "homepage.hero.subtitle": "Por traducir",
    "homepage.hero.cta": "Por traducir",
    "homepage.cta.title": "Por traducir",
    "homepage.cta.highlight": "Por traducir",
    "homepage.cta.subtitle": "Por traducir",
    "homepage.cta.button": "Por traducir",
    "homepage.final.title": "Por traducir",
    "homepage.final.subtitle": "Por traducir",
    "homepage.final.button": "Por traducir"
  },

  es: {
    "footer.company": "Chine ton usine",
    "footer.about": "Acerca de",
    "footer.careers": "Carreras",
    "footer.news": "Noticias",
    "footer.solutions": "Soluciones",
    "footer.sourcing": "Abastecimiento",
    "footer.quality": "Calidad",
    "footer.logistics": "Logística",
    "footer.resources": "Recursos",
    "footer.help": "Centro de ayuda",
    "footer.blog": "Blog",
    "footer.guides": "Guías",
    "footer.legal": "Legal",
    "footer.privacy": "Privacidad",
    "footer.terms": "Condiciones",
    "footer.cookies": "Cookies",
    "footer.contact": "Contacto",
    "footer.contactus": "Contáctanos",
    "footer.email": "Correo electrónico",
    "footer.phone": "Teléfono",
    "footer.copyright": "Chine ton usine",
    "footer.rights": "Todos los derechos reservados",
    "home": "Inicio",
    "search": "Buscar",
    "search.placeholder": "Buscar productos...",
    "dashboard": "Panel",
    "nav.login": "Iniciar Sesión",
    "logout": "Cerrar Sesión",
    "discover": "Descubrir",

    // Authentication
    "email": "Email",
    "password": "Contraseña",
    "confirmPassword": "Confirmar Contraseña",
    "login": "Iniciar Sesión",
    "register": "Registrarse",
    "loginDescription": "Inicia sesión para acceder a tu cuenta",
    "accountType": "Tipo de Cuenta",
    "role.customer": "Cliente",
    "role.supplier": "Proveedor",
    "role.sourcer": "Buscador",
    "role.influencer": "Influencer",

    // SupplierProfile Page translations
    "supplier.loadingProfile": "Cargando perfil...",
    "supplier.goldSupplier": "Proveedor de Oro",
    "supplier.reviews": "reseñas",
    "supplier.since": "Desde",
    "supplier.contact": "Contacto",
    "supplier.viewProducts": "Ver Productos",
    "supplier.overview": "Resumen",
    "supplier.products": "Productos",
    "supplier.businessCards": "Tarjetas de Negocio",
    "supplier.certifications": "Certificaciones",
    "supplier.gallery": "Galería",
    "supplier.aboutCompany": "Acerca de la Empresa",
    "supplier.specialties": "Especialidades",
    "supplier.performance": "Rendimiento",
    "supplier.ordersCompleted": "Pedidos Completados",
    "supplier.responseTime": "Tiempo de Respuesta",
    "supplier.onTimeDelivery": "Entrega a Tiempo",
    "supplier.viewAll": "Ver Todo",
    "supplier.myBusinessCards": "Mis Tarjetas de Negocio",
    "supplier.createBusinessCardsDesc": "Crea y personaliza tus tarjetas de negocio profesionales. Compártelas fácilmente con tus clientes y socios.",
    "supplier.viewBusinessCardsDesc": "Descubre las tarjetas de negocio de este proveedor y descárgalas para tus contactos.",
    "supplier.businessCardsAvailable": "Tarjetas de Negocio Disponibles",
    "supplier.supplierSharesCards": "Este proveedor comparte sus tarjetas de negocio con socios.",
    "supplier.certificationsAndStandards": "Certificaciones y Estándares",
    "supplier.validCertification": "Certificación Válida",
    "supplier.companyGallery": "Galería de la Empresa",
    "supplier.customerReviews": "Reseñas de Clientes",
    "supplier.weeksAgo": "hace {{count}} semana{{count, plural, one {} other {s}}}",
    "supplier.sampleReviewText": "¡Excelente proveedor! Calidad de producto impecable y entrega muy rápida. Lo recomiendo mucho.",
    "supplier.helpful": "Útil",
    "supplier.reply": "Responder",
    "supplier.contactInfo": "Información de Contacto",
    "supplier.address": "Dirección",
    "supplier.phone": "Teléfono",
    "supplier.email": "Email",
    "supplier.website": "Sitio Web",
    "supplier.companyInfo": "Información de la Empresa",
    "supplier.foundedIn": "Fundada en",
    "supplier.employees": "Empleados",
    "supplier.quickActions": "Acciones Rápidas",
    "supplier.sendMessage": "Enviar Mensaje",
    "supplier.requestQuote": "Solicitar Cotización",
    "supplier.downloadCatalog": "Descargar Catálogo",

    // Homepage cards
    "homepage.cards.technology": "Tecnología",
    "homepage.cards.electronics": "Electrónica",
    "homepage.cards.electronics.description": "Descubre las últimas innovaciones electrónicas",
    "homepage.cards.explore": "Explorar",
    "homepage.cards.fashion.title": "Moda",
    "homepage.cards.textile": "Textil",
    "homepage.cards.textile.description": "Tejidos de calidad para todas tus necesidades",
    "homepage.cards.industrial": "Industrial",
    "homepage.cards.machinery": "Maquinaria",
    "homepage.cards.machinery.description": "Equipos industriales de alta calidad",
    "homepage.cards.new": "Nuevo",
    "homepage.cards.decoration": "Decoración",
    "homepage.cards.home.garden": "Hogar y Jardín",
    "homepage.cards.home.garden.description": "Transforma tu espacio vital",
    "homepage.cards.educational": "Educativo",
    "homepage.cards.toys.children": "Juguetes y Niños",
    "homepage.cards.toys.description": "Juguetes seguros y educativos para niños",
    "homepage.cards.parts": "Piezas",

    // Homepage stats
    "homepage.stats.products": "Productos",
    "homepage.stats.suppliers": "Proveedores",
    "homepage.stats.satisfaction": "Satisfacción",
    "homepage.stats.response": "Respuesta",
    "homepage.categories.popular": "Categorías Populares",
    "homepage.categories.popular.subtitle": "Descubre nuestras categorías más solicitadas",
    "homepage.search.placeholder.dev": "🚧 Nueva interfaz en desarrollo...",

    "homepage.cards.auto.moto": "Auto y Moto",
    "homepage.cards.auto.description": "Piezas y accesorios automotrices",

    // Homepage sections
    "homepage.categories.section.title": "Explorar por categoría",
    "homepage.categories.section.subtitle": "Encuentra rápidamente lo que buscas",
    "homepage.recommendations.loading": "Cargando recomendaciones...",
    "homepage.recommendations.badge": "Tendencias",
    "homepage.recommendations.title": "Recomendado para ti",
    "homepage.recommendations.subtitle": "Descubre nuestras selecciones personalizadas",
    "homepage.recommendations.viewAll": "Ver todo",
    "homepage.recommendations.discover": "Descubrir",
    "homepage.cta.title": "Te va a",
    "homepage.cta.highlight": "ENCANTAR",
    "homepage.cta.subtitle": "Amor a primera vista inevitable.",
    "homepage.cta.button": "Descubrir nuestros productos",

    // Sourcer Dashboard
    "sourcer.dashboard.title": "Panel de Sourcer",
    "sourcer.dashboard.description": "Interfaz de gestión para sourcers.",
    "sourcer.dashboard.comingSoon": "Función próximamente",

    // Homepage benefits
    "homepage.benefits.delivery.title": "Entrega Rápida",
    "homepage.benefits.delivery.description": "Envío en 24-48h en toda España",
    "homepage.benefits.payment.title": "Pago Seguro",
    "homepage.benefits.payment.description": "Transacciones protegidas y garantizadas",
    "homepage.benefits.support.title": "Soporte 24/7",
    "homepage.benefits.support.description": "Un equipo dedicado a tu servicio",

    // Homepage how it works
    "homepage.how.title": "¿Cómo funciona?",
    "homepage.how.subtitle": "Tres pasos simples para ordenar desde China",
    "homepage.how.step1.title": "1. Buscar",
    "homepage.how.step1.description": "Encuentra el producto perfecto entre miles de referencias",
    "homepage.how.step2.title": "2. Contactar",
    "homepage.how.step2.description": "Intercambia directamente con proveedores verificados",
    "homepage.how.step3.title": "3. Ordenar",
    "homepage.how.step3.description": "Finaliza tu compra de forma segura",
    "homepage.how.cta": "Comenzar ahora",

    // Homepage optimization
    "homepage.optimize.title": "Optimiza tus pedidos",
    "homepage.optimize.search.title": "Buscar ofertas",
    "homepage.optimize.search.description": "Navega miles de productos y encuentra las mejores ofertas",
    "homepage.optimize.identify.title": "Identifica el proveedor correcto",
    "homepage.optimize.identify.description": "Compara proveedores y elige el mejor para tus necesidades",
    "homepage.optimize.pay.title": "Paga con confianza",
    "homepage.optimize.pay.description": "Transacciones seguras con protección al comprador",
    "homepage.optimize.manage.title": "Gestiona fácilmente",
    "homepage.optimize.manage.description": "Rastrea tus pedidos y gestiona tus relaciones con proveedores",

    // Homepage discover
    "homepage.discover.network": "Red global",
    "homepage.discover.title": "Descubre todos nuestros proveedores",
    "homepage.discover.highlight": "verificados",
    "homepage.discover.subtitle": "Conéctate con más de 1000 proveedores verificados en todo el mundo",
    "homepage.discover.button": "Explorar proveedores",
    "homepage.discover.verified": "Más de 1000 proveedores verificados",

    // Homepage process
    "homepage.process.title": "Nuestro proceso simplificado",
    "homepage.process.subtitle": "Desde la búsqueda hasta la entrega, te acompañamos en cada paso",
    "homepage.process.step1.title": "Búsqueda",
    "homepage.process.step1.description": "Encuentra tus productos",
    "homepage.process.step2.title": "Contacto",
    "homepage.process.step2.description": "Intercambia con proveedores",
    "homepage.process.step3.title": "Pedido",
    "homepage.process.step3.description": "Realiza tu pedido",
    "homepage.process.step4.title": "Pago",
    "homepage.process.step4.description": "Paga de forma segura",
    "homepage.process.cta": "Comenzar ahora",

    // Homepage final CTA
    "homepage.final.title": "¿Listo para comenzar?",
    "homepage.final.subtitle": "Únete a miles de empresas que confían en nuestra plataforma",
    "homepage.final.button": "Crear mi cuenta",

    // Common
    "units": "unidades",
    "cbm": "CBM",
    "cancel": "Cancelar",
    "confirm": "Confirmar",
    "close": "Cerrar",

    // --- AJOUT DES CLÉS MANQUANTES POUR LA PAGE D'ACCUEIL DANS TOUTES LES LANGUES ---
    // Pour chaque bloc de langue (fr, en, es, ar, zh, pt, de), je complète les clés manquantes de la page d'accueil
    // Les valeurs sont traduites ou, à défaut, un placeholder est utilisé

    // Exemple pour le bloc espagnol (à placer dans le bloc 'es')
    "homepage.title": "Por traducir",
    "homepage.subtitle": "Por traducir",
    "homepage.subtitle.highlight": "Por traducir",
    "homepage.tagline": "Por traducir",
    "homepage.hero.title": "Por traducir",
    "homepage.hero.subtitle": "Por traducir",
    "homepage.hero.cta": "Por traducir",
    "homepage.cta.title": "Por traducir",
    "homepage.cta.highlight": "Por traducir",
    "homepage.cta.subtitle": "Por traducir",
    "homepage.cta.button": "Por traducir",
    "homepage.final.title": "Por traducir",
    "homepage.final.subtitle": "Por traducir",
    "homepage.final.button": "Por traducir"
  },

  ar: {
    "footer.company": "تشاين تون أوزين",
    "footer.about": "حول",
    "footer.careers": "وظائف",
    "footer.news": "أخبار",
    "footer.solutions": "الحلول",
    "footer.sourcing": "التوريد",
    "footer.quality": "الجودة",
    "footer.logistics": "الخدمات اللوجستية",
    "footer.resources": "الموارد",
    "footer.help": "مركز المساعدة",
    "footer.blog": "مدونة",
    "footer.guides": "أدلة",
    "footer.legal": "قانوني",
    "footer.privacy": "الخصوصية",
    "footer.terms": "الشروط",
    "footer.cookies": "ملفات تعريف الارتباط",
    "footer.contact": "اتصال",
    "footer.contactus": "اتصل بنا",
    "footer.email": "البريد الإلكتروني",
    "footer.phone": "الهاتف",
    "footer.copyright": "تشاين تون أوزين",
    "footer.rights": "جميع الحقوق محفوظة",
    "home": "الرئيسية",
    "search": "بحث",
    "search.placeholder": "البحث عن المنتجات...",
    "dashboard": "لوحة القيادة",
    "nav.login": "تسجيل الدخول",
    "logout": "تسجيل الخروج",
    "discover": "اكتشف",

    // Authentication
    "email": "البريد الإلكتروني",
    "password": "كلمة المرور",
    "confirmPassword": "تأكيد كلمة المرور",
    "login": "تسجيل الدخول",
    "register": "التسجيل",
    "loginDescription": "قم بتسجيل الدخول للوصول إلى حسابك",
    "accountType": "نوع الحساب",
    "role.customer": "عميل",
    "role.supplier": "مورد",
    "role.sourcer": "باحث",
    "role.influencer": "مؤثر",

    // SupplierProfile Page translations
    "supplier.loadingProfile": "جاري تحميل الملف الشخصي...",
    "supplier.goldSupplier": "مورد ذهبي",
    "supplier.reviews": "مراجعات",
    "supplier.since": "منذ",
    "supplier.contact": "اتصال",
    "supplier.viewProducts": "عرض المنتجات",
    "supplier.overview": "نظرة عامة",
    "supplier.products": "المنتجات",
    "supplier.businessCards": "بطاقات العمل",
    "supplier.certifications": "الشهادات",
    "supplier.gallery": "المعرض",
    "supplier.aboutCompany": "حول الشركة",
    "supplier.specialties": "التخصصات",
    "supplier.performance": "الأداء",
    "supplier.ordersCompleted": "الطلبات المكتملة",
    "supplier.responseTime": "وقت الاستجابة",
    "supplier.onTimeDelivery": "التسليم في الوقت المحدد",
    "supplier.viewAll": "عرض الكل",
    "supplier.myBusinessCards": "بطاقات العمل الخاصة بي",
    "supplier.createBusinessCardsDesc": "أنشئ وخصص بطاقات العمل المهنية الخاصة بك. شاركها بسهولة مع عملائك وشركائك.",
    "supplier.viewBusinessCardsDesc": "اكتشف بطاقات عمل هذا المورد وحملها لجهات الاتصال الخاصة بك.",
    "supplier.businessCardsAvailable": "بطاقات العمل متاحة",
    "supplier.supplierSharesCards": "يشارك هذا المورد بطاقات عمله مع الشركاء.",
    "supplier.certificationsAndStandards": "الشهادات والمعايير",
    "supplier.validCertification": "شهادة صالحة",
    "supplier.companyGallery": "معرض الشركة",
    "supplier.customerReviews": "مراجعات العملاء",
    "supplier.weeksAgo": "منذ {{count}} أسبوع{{count, plural, one {} other {}}}",
    "supplier.sampleReviewText": "مورد ممتاز! جودة منتج لا تشوبها شائبة وتسليم سريع جداً. أنصح بشدة.",
    "supplier.helpful": "مفيد",
    "supplier.reply": "رد",
    "supplier.contactInfo": "معلومات الاتصال",
    "supplier.address": "العنوان",
    "supplier.phone": "الهاتف",
    "supplier.email": "البريد الإلكتروني",
    "supplier.website": "الموقع الإلكتروني",
    "supplier.companyInfo": "معلومات الشركة",
    "supplier.foundedIn": "تأسست في",
    "supplier.employees": "الموظفون",
    "supplier.quickActions": "إجراءات سريعة",
    "supplier.sendMessage": "إرسال رسالة",
    "supplier.requestQuote": "طلب عرض أسعار",
    "supplier.downloadCatalog": "تنزيل الكتالوج",

    // Homepage cards
    "homepage.cards.technology": "التكنولوجيا",
    "homepage.cards.electronics": "الإلكترونيات",
    "homepage.cards.electronics.description": "اكتشف أحدث الابتكارات الإلكترونية",
    "homepage.cards.explore": "استكشف",
    "homepage.cards.fashion.title": "الموضة",
    "homepage.cards.textile": "النسيج",
    "homepage.cards.textile.description": "أقمشة عالية الجودة لجميع احتياجاتك",
    "homepage.cards.industrial": "صناعي",
    "homepage.cards.machinery": "الآلات",
    "homepage.cards.machinery.description": "معدات صناعية عالية الجودة",
    "homepage.cards.new": "جديد",
    "homepage.cards.decoration": "الديكور",
    "homepage.cards.home.garden": "المنزل والحديقة",
    "homepage.cards.home.garden.description": "حول مساحة معيشتك",
    "homepage.cards.educational": "تعليمي",
    "homepage.cards.toys.children": "الألعاب والأطفال",
    "homepage.cards.toys.description": "ألعاب آمنة وتعليمية للأطفال",
    "homepage.cards.parts": "قطع الغيار",

    // Homepage stats
    "homepage.stats.products": "المنتجات",
    "homepage.stats.suppliers": "الموردين",
    "homepage.stats.satisfaction": "الرضا",
    "homepage.stats.response": "الاستجابة",
    "homepage.categories.popular": "الفئات الشائعة",
    "homepage.categories.popular.subtitle": "اكتشف أكثر الفئات طلبًا لدينا",
    "homepage.search.placeholder.dev": "🚧 واجهة جديدة قيد التطوير...",

    "homepage.cards.auto.moto": "السيارات والدراجات النارية",
    "homepage.cards.auto.description": "قطع غيار ومستلزمات السيارات",

    // Homepage sections
    "homepage.categories.section.title": "استكشف حسب الفئة",
    "homepage.categories.section.subtitle": "اعثر بسرعة على ما تبحث عنه",
    "homepage.recommendations.loading": "تحميل التوصيات...",
    "homepage.recommendations.badge": "الاتجاهات",
    "homepage.recommendations.title": "موصى به لك",
    "homepage.recommendations.subtitle": "اكتشف مجموعاتنا الشخصية",
    "homepage.recommendations.viewAll": "عرض الكل",
    "homepage.recommendations.discover": "اكتشف",

    // Sourcer Dashboard
    "sourcer.dashboard.title": "لوحة تحكم المورد",
    "sourcer.dashboard.description": "واجهة إدارة للموردين.",
    "sourcer.dashboard.comingSoon": "الميزة قريباً",

    // Homepage benefits
    "homepage.benefits.delivery.title": "التسليم السريع",
    "homepage.benefits.delivery.description": "الشحن خلال 24-48 ساعة",
    "homepage.benefits.payment.title": "الدفع الآمن",
    "homepage.benefits.payment.description": "معاملات محمية ومضمونة",
    "homepage.benefits.support.title": "الدعم 24/7",
    "homepage.benefits.support.description": "فريق مخصص في خدمتك",

    // Homepage discover
    "homepage.discover.network": "شبكة عالمية",
    "homepage.discover.title": "اكتشف جميع مورديناناتهم",
    "homepage.discover.highlight": "المعتمدين",
    "homepage.discover.subtitle": "تواصل مع أكثر من 1000 مورد معتمد حول العالم",
    "homepage.discover.button": "استكشاف الموردين",
    "homepage.discover.verified": "أكثر من 1000 مورد معتمد",

    // Common
    "units": "وحدات",
    "cbm": "CBM",
    "cancel": "إلغاء",
    "confirm": "تأكيد",
    "close": "إغلاق",

    // --- AJOUT DES CLÉS MANQUANTES POUR LA PAGE D'ACCUEIL DANS TOUTES LES LANGUES ---
    // Pour chaque bloc de langue (fr, en, es, ar, zh, pt, de), je complète les clés manquantes de la page d'accueil
    // Les valeurs sont traduites ou, à défaut, un placeholder est utilisé

    // Exemple pour le bloc espagnol (à placer dans le bloc 'es')
    "homepage.title": "Por traducir",
    "homepage.subtitle": "Por traducir",
    "homepage.subtitle.highlight": "Por traducir",
    "homepage.tagline": "Por traducir",
    "homepage.hero.title": "Por traducir",
    "homepage.hero.subtitle": "Por traducir",
    "homepage.hero.cta": "Por traducir",
    "homepage.cta.title": "Por traducir",
    "homepage.cta.highlight": "Por traducir",
    "homepage.cta.subtitle": "Por traducir",
    "homepage.cta.button": "Por traducir",
    "homepage.final.title": "Por traducir",
    "homepage.final.subtitle": "Por traducir",
    "homepage.final.button": "Por traducir"
  },

  zh: {
    "footer.company": "Chine ton usine",
    "footer.about": "关于我们",
    "footer.careers": "招聘",
    "footer.news": "新闻",
    "footer.solutions": "解决方案",
    "footer.sourcing": "采购",
    "footer.quality": "质量",
    "footer.logistics": "物流",
    "footer.resources": "资源",
    "footer.help": "帮助中心",
    "footer.blog": "博客",
    "footer.guides": "指南",
    "footer.legal": "法律",
    "footer.privacy": "隐私",
    "footer.terms": "条款",
    "footer.cookies": "Cookies",
    "footer.contact": "联系",
    "footer.contactus": "联系我们",
    "footer.email": "电子邮件",
    "footer.phone": "电话",
    "footer.copyright": "Chine ton usine",
    "footer.rights": "保留所有权利",
    "home": "首页",
    "search": "搜索",
    "search.placeholder": "搜索产品...",
    "dashboard": "仪表板",
    "nav.login": "登录",
    "logout": "退出",
    "discover": "发现",

    // Authentication
    "email": "邮箱",
    "password": "密码",
    "confirmPassword": "确认密码",
    "login": "登录",
    "register": "注册",
    "loginDescription": "登录以访问您的账户",
    "accountType": "账户类型",
    "role.customer": "客户",
    "role.supplier": "供应商",
    "role.sourcer": "采购商",
    "role.influencer": "影响者",

    // SupplierProfile Page translations
    "supplier.loadingProfile": "正在加载档案...",
    "supplier.goldSupplier": "金牌供应商",
    "supplier.reviews": "评价",
    "supplier.since": "自从",
    "supplier.contact": "联系",
    "supplier.viewProducts": "查看产品",
    "supplier.overview": "概览",
    "supplier.products": "产品",
    "supplier.businessCards": "名片",
    "supplier.certifications": "认证",
    "supplier.gallery": "画廊",
    "supplier.aboutCompany": "关于公司",
    "supplier.specialties": "专业",
    "supplier.performance": "业绩",
    "supplier.ordersCompleted": "已完成订单",
    "supplier.responseTime": "响应时间",
    "supplier.onTimeDelivery": "按时交付",
    "supplier.viewAll": "查看全部",
    "supplier.myBusinessCards": "我的名片",
    "supplier.createBusinessCardsDesc": "创建和自定义您的专业名片。轻松与您的客户和合作伙伴分享。",
    "supplier.viewBusinessCardsDesc": "发现此供应商的名片并下载到您的联系人。",
    "supplier.businessCardsAvailable": "可用名片",
    "supplier.supplierSharesCards": "此供应商与合作伙伴分享名片。",
    "supplier.certificationsAndStandards": "认证和标准",
    "supplier.validCertification": "有效认证",
    "supplier.companyGallery": "公司画廊",
    "supplier.customerReviews": "客户评价",
    "supplier.weeksAgo": "{{count}}周前",
    "supplier.sampleReviewText": "优秀的供应商！产品质量完美，交付非常快。我强烈推荐。",
    "supplier.helpful": "有用",
    "supplier.reply": "回复",
    "supplier.contactInfo": "联系信息",
    "supplier.address": "地址",
    "supplier.phone": "电话",
    "supplier.email": "邮箱",
    "supplier.website": "网站",
    "supplier.companyInfo": "公司信息",
    "supplier.foundedIn": "成立于",
    "supplier.employees": "员工",
    "supplier.quickActions": "快速操作",
    "supplier.sendMessage": "发送消息",
    "supplier.requestQuote": "请求报价",
    "supplier.downloadCatalog": "下载目录",

    // Homepage cards
    "homepage.cards.technology": "技术",
    "homepage.cards.electronics": "电子产品",
    "homepage.cards.electronics.description": "发现最新的电子创新",
    "homepage.cards.explore": "探索",
    "homepage.cards.fashion.title": "时尚",
    "homepage.cards.textile": "纺织品",
    "homepage.cards.textile.description": "满足您所有需求的优质面料",
    "homepage.cards.industrial": "工业",
    "homepage.cards.machinery": "机械",
    "homepage.cards.machinery.description": "高质量工业设备",
    "homepage.cards.new": "新品",
    "homepage.cards.decoration": "装饰",
    "homepage.cards.home.garden": "家居园艺",
    "homepage.cards.home.garden.description": "改造您的生活空间",
    "homepage.cards.educational": "教育",
    "homepage.cards.toys.children": "玩具儿童",
    "homepage.cards.toys.description": "安全教育的儿童玩具",
    "homepage.cards.parts": "零件",

    // Homepage stats
    "homepage.stats.products": "产品",
    "homepage.stats.suppliers": "供应商",
    "homepage.stats.satisfaction": "满意度",
    "homepage.stats.response": "响应",
    "homepage.categories.popular": "热门类别",
    "homepage.categories.popular.subtitle": "探索我们最受欢迎的类别",
    "homepage.search.placeholder.dev": "🚧 新界面开发中...",

    "homepage.cards.auto.moto": "汽车摩托",
    "homepage.cards.auto.description": "汽车零件和配件",

    // Homepage sections
    "homepage.categories.section.title": "按类别探索",
    "homepage.categories.section.subtitle": "快速找到您需要的内容",
    "homepage.recommendations.loading": "加载推荐...",
    "homepage.recommendations.badge": "热门",
    "homepage.recommendations.title": "为您推荐",
    "homepage.recommendations.subtitle": "发现我们的个性化选择",
    "homepage.recommendations.viewAll": "查看全部",
    "homepage.recommendations.discover": "发现",

    // Sourcer Dashboard
    "sourcer.dashboard.title": "采购员仪表板",
    "sourcer.dashboard.description": "采购员管理界面。",
    "sourcer.dashboard.comingSoon": "功能即将推出",

    // Homepage benefits
    "homepage.benefits.delivery.title": "快速配送",
    "homepage.benefits.delivery.description": "24-48小时内发货",
    "homepage.benefits.payment.title": "安全支付",
    "homepage.benefits.payment.description": "受保护和保证的交易",
    "homepage.benefits.support.title": "24/7支持",
    "homepage.benefits.support.description": "专门团队为您服务",

    // Homepage discover
    "homepage.discover.network": "全球网络",
    "homepage.discover.title": "发现我们所有的供应商",
    "homepage.discover.highlight": "已验证",
    "homepage.discover.subtitle": "与全球1000多家经过验证的供应商联系",
    "homepage.discover.button": "探索供应商",
    "homepage.discover.verified": "1000多家经过验证的供应商",

    // Common
    "units": "单位",
    "cbm": "CBM",
    "cancel": "取消",
    "confirm": "确认",
    "close": "关闭",

    // --- AJOUT DES CLÉS MANQUANTES POUR LA PAGE D'ACCUEIL DANS TOUTES LES LANGUES ---
    // Pour chaque bloc de langue (fr, en, es, ar, zh, pt, de), je complète les clés manquantes de la page d'accueil
    // Les valeurs sont traduites ou, à défaut, un placeholder est utilisé

    // Exemple pour le bloc espagnol (à placer dans le bloc 'es')
    "homepage.title": "Por traducir",
    "homepage.subtitle": "Por traducir",
    "homepage.subtitle.highlight": "Por traducir",
    "homepage.tagline": "Por traducir",
    "homepage.hero.title": "Por traducir",
    "homepage.hero.subtitle": "Por traducir",
    "homepage.hero.cta": "Por traducir",
    "homepage.cta.title": "Por traducir",
    "homepage.cta.highlight": "Por traducir",
    "homepage.cta.subtitle": "Por traducir",
    "homepage.cta.button": "Por traducir",
    "homepage.final.title": "Por traducir",
    "homepage.final.subtitle": "Por traducir",
    "homepage.final.button": "Por traducir"
  },

  pt: {
    "footer.company": "Chine ton usine",
    "footer.about": "Sobre",
    "footer.careers": "Carreiras",
    "footer.news": "Notícias",
    "footer.solutions": "Soluções",
    "footer.sourcing": "Sourcing",
    "footer.quality": "Qualidade",
    "footer.logistics": "Logística",
    "footer.resources": "Recursos",
    "footer.help": "Central de Ajuda",
    "footer.blog": "Blog",
    "footer.guides": "Guias",
    "footer.legal": "Legal",
    "footer.privacy": "Privacidade",
    "footer.terms": "Termos",
    "footer.cookies": "Cookies",
    "footer.contact": "Contato",
    "footer.contactus": "Fale conosco",
    "footer.email": "Email",
    "footer.phone": "Telefone",
    "footer.copyright": "Chine ton usine",
    "footer.rights": "Todos os direitos reservados",
    "home": "Início",
    "search": "Pesquisar",
    "search.placeholder": "Pesquisar produtos...",
    "dashboard": "Painel",
    "nav.login": "Entrar",
    "logout": "Sair",
    "discover": "Descobrir",

    // Authentication
    "email": "Email",
    "password": "Senha",
    "confirmPassword": "Confirmar Senha",
    "login": "Entrar",
    "register": "Registrar",
    "loginDescription": "Entre para acessar sua conta",
    "accountType": "Tipo de Conta",
    "role.customer": "Cliente",
    "role.supplier": "Fornecedor",
    "role.sourcer": "Sourcer",
    "role.influencer": "Influenciador",

    // SupplierProfile Page translations
    "supplier.loadingProfile": "Carregando perfil...",
    "supplier.goldSupplier": "Fornecedor Gold",
    "supplier.reviews": "avaliações",
    "supplier.since": "Desde",
    "supplier.contact": "Contato",
    "supplier.viewProducts": "Ver Produtos",
    "supplier.overview": "Visão Geral",
    "supplier.products": "Produtos",
    "supplier.businessCards": "Cartões de Visita",
    "supplier.certifications": "Certificações",
    "supplier.gallery": "Galeria",
    "supplier.aboutCompany": "Sobre a Empresa",
    "supplier.specialties": "Especialidades",
    "supplier.performance": "Desempenho",
    "supplier.ordersCompleted": "Pedidos Concluídos",
    "supplier.responseTime": "Tempo de Resposta",
    "supplier.onTimeDelivery": "Entrega Pontual",
    "supplier.viewAll": "Ver Tudo",
    "supplier.myBusinessCards": "Meus Cartões de Visita",
    "supplier.createBusinessCardsDesc": "Crie e personalize seus cartões de visita profissionais. Compartilhe facilmente com seus clientes e parceiros.",
    "supplier.viewBusinessCardsDesc": "Descubra os cartões de visita deste fornecedor e baixe para seus contatos.",
    "supplier.businessCardsAvailable": "Cartões de Visita Disponíveis",
    "supplier.supplierSharesCards": "Este fornecedor compartilha cartões de visita com parceiros.",
    "supplier.certificationsAndStandards": "Certificações e Padrões",
    "supplier.validCertification": "Certificação Válida",
    "supplier.companyGallery": "Galeria da Empresa",
    "supplier.customerReviews": "Avaliações de Clientes",
    "supplier.weeksAgo": "{{count}} semana{{count, plural, one {} other {s}}} atrás",
    "supplier.sampleReviewText": "Excelente fornecedor! Qualidade do produto impecável e entrega muito rápida. Recomendo muito.",
    "supplier.helpful": "Útil",
    "supplier.reply": "Responder",
    "supplier.contactInfo": "Informações de Contato",
    "supplier.address": "Endereço",
    "supplier.phone": "Telefone",
    "supplier.email": "Email",
    "supplier.website": "Site",
    "supplier.companyInfo": "Informações da Empresa",
    "supplier.foundedIn": "Fundada em",
    "supplier.employees": "Funcionários",
    "supplier.quickActions": "Ações Rápidas",
    "supplier.sendMessage": "Enviar Mensagem",
    "supplier.requestQuote": "Solicitar Cotação",
    "supplier.downloadCatalog": "Baixar Catálogo",

    // Homepage cards
    "homepage.cards.technology": "Tecnologia",
    "homepage.cards.electronics": "Eletrônicos",
    "homepage.cards.electronics.description": "Descubra as últimas inovações eletrônicas",
    "homepage.cards.explore": "Explorar",
    "homepage.cards.fashion.title": "Moda",
    "homepage.cards.textile": "Têxtil",
    "homepage.cards.textile.description": "Tecidos de qualidade para todas as suas necessidades",
    "homepage.cards.industrial": "Industrial",
    "homepage.cards.machinery": "Maquinário",
    "homepage.cards.machinery.description": "Equipamentos industriais de alta qualidade",
    "homepage.cards.new": "Novo",
    "homepage.cards.decoration": "Decoração",
    "homepage.cards.home.garden": "Casa e Jardim",
    "homepage.cards.home.garden.description": "Transforme seu espaço de vida",
    "homepage.cards.educational": "Educacional",
    "homepage.cards.toys.children": "Brinquedos e Crianças",
    "homepage.cards.toys.description": "Brinquedos seguros e educacionais para crianças",
    "homepage.cards.parts": "Peças",

    // Homepage stats
    "homepage.stats.products": "Produtos",
    "homepage.stats.suppliers": "Fornecedores",
    "homepage.stats.satisfaction": "Satisfação",
    "homepage.stats.response": "Resposta",
    "homepage.categories.popular": "Categorias Populares",
    "homepage.categories.popular.subtitle": "Descubra nossas categorias mais procuradas",
    "homepage.search.placeholder.dev": "🚧 Nova interface em desenvolvimento...",

    "homepage.cards.auto.moto": "Auto e Moto",
    "homepage.cards.auto.description": "Peças e acessórios automotivos",

    // Homepage sections
    "homepage.categories.section.title": "Explore por categoria",
    "homepage.categories.section.subtitle": "Encontre rapidamente o que procura",
    "homepage.recommendations.loading": "Carregando recomendações...",
    "homepage.recommendations.badge": "Tendências",
    "homepage.recommendations.title": "Recomendado para você",
    "homepage.recommendations.subtitle": "Descubra nossas seleções personalizadas",
    "homepage.recommendations.viewAll": "Ver tudo",
    "homepage.recommendations.discover": "Descobrir",

    // Sourcer Dashboard
    "sourcer.dashboard.title": "Painel do Sourcer",
    "sourcer.dashboard.description": "Interface de gestão para sourcers.",
    "sourcer.dashboard.comingSoon": "Funcionalidade em breve",

    // Homepage benefits
    "homepage.benefits.delivery.title": "Entrega Rápida",
    "homepage.benefits.delivery.description": "Envio em 24-48h",
    "homepage.benefits.payment.title": "Pagamento Seguro",
    "homepage.benefits.payment.description": "Transações protegidas e garantidas",
    "homepage.benefits.support.title": "Suporte 24/7",
    "homepage.benefits.support.description": "Uma equipe dedicada ao seu serviço",

    // Homepage discover
    "homepage.discover.network": "Rede global",
    "homepage.discover.title": "Descubra todos os nossos fornecedores",
    "homepage.discover.highlight": "verificados",
    "homepage.discover.subtitle": "Conecte-se com mais de 1000 fornecedores verificados mundialmente",
    "homepage.discover.button": "Explorar fornecedores",
    "homepage.discover.verified": "Mais de 1000 fornecedores verificados",

    // Common
    "units": "unidades",
    "cbm": "CBM",
    "cancel": "Cancelar",
    "confirm": "Confirmar",
    "close": "Fechar",

    // --- AJOUT DES CLÉS MANQUANTES POUR LA PAGE D'ACCUEIL DANS TOUTES LES LANGUES ---
    // Pour chaque bloc de langue (fr, en, es, ar, zh, pt, de), je complète les clés manquantes de la page d'accueil
    // Les valeurs sont traduites ou, à défaut, un placeholder est utilisé

    // Exemple pour le bloc espagnol (à placer dans le bloc 'es')
    "homepage.title": "Por traducir",
    "homepage.subtitle": "Por traducir",
    "homepage.subtitle.highlight": "Por traducir",
    "homepage.tagline": "Por traducir",
    "homepage.hero.title": "Por traducir",
    "homepage.hero.subtitle": "Por traducir",
    "homepage.hero.cta": "Por traducir",
    "homepage.cta.title": "Por traducir",
    "homepage.cta.highlight": "Por traducir",
    "homepage.cta.subtitle": "Por traducir",
    "homepage.cta.button": "Por traducir",
    "homepage.final.title": "Por traducir",
    "homepage.final.subtitle": "Por traducir",
    "homepage.final.button": "Por traducir"
  },

  de: {
    "footer.company": "Chine ton usine",
    "footer.about": "Über uns",
    "footer.careers": "Karriere",
    "footer.news": "Neuigkeiten",
    "footer.solutions": "Lösungen",
    "footer.sourcing": "Beschaffung",
    "footer.quality": "Qualität",
    "footer.logistics": "Logistik",
    "footer.resources": "Ressourcen",
    "footer.help": "Hilfezentrum",
    "footer.blog": "Blog",
    "footer.guides": "Leitfäden",
    "footer.legal": "Rechtliches",
    "footer.privacy": "Datenschutz",
    "footer.terms": "Bedingungen",
    "footer.cookies": "Cookies",
    "footer.contact": "Kontakt",
    "footer.contactus": "Kontaktieren Sie uns",
    "footer.email": "E-Mail",
    "footer.phone": "Telefon",
    "footer.copyright": "Chine ton usine",
    "footer.rights": "Alle Rechte vorbehalten",
    "home": "Startseite",
    "search": "Suchen",
    "search.placeholder": "Produkte suchen...",
    "dashboard": "Dashboard",
    "nav.login": "Anmelden",
    "logout": "Abmelden",
    "discover": "Entdecken",

    // Authentication
    "email": "E-Mail",
    "password": "Passwort",
    "confirmPassword": "Passwort bestätigen",
    "login": "Anmelden",
    "register": "Registrieren",
    "loginDescription": "Melden Sie sich an, um auf Ihr Konto zuzugreifen",
    "accountType": "Kontotyp",
    "role.customer": "Kunde",
    "role.supplier": "Lieferant",
    "role.sourcer": "Beschaffer",
    "role.influencer": "Influencer",

    // SupplierProfile Page translations
    "supplier.loadingProfile": "Profil wird geladen...",
    "supplier.goldSupplier": "Gold-Lieferant",
    "supplier.reviews": "Bewertungen",
    "supplier.since": "Seit",
    "supplier.contact": "Kontakt",
    "supplier.viewProducts": "Produkte anzeigen",
    "supplier.overview": "Übersicht",
    "supplier.products": "Produkte",
    "supplier.businessCards": "Visitenkarten",
    "supplier.certifications": "Zertifizierungen",
    "supplier.gallery": "Galerie",
    "supplier.aboutCompany": "Über das Unternehmen",
    "supplier.specialties": "Spezialitäten",
    "supplier.performance": "Leistung",
    "supplier.ordersCompleted": "Abgeschlossene Bestellungen",
    "supplier.responseTime": "Antwortzeit",
    "supplier.onTimeDelivery": "Pünktliche Lieferung",
    "supplier.viewAll": "Alle anzeigen",
    "supplier.myBusinessCards": "Meine Visitenkarten",
    "supplier.createBusinessCardsDesc": "Erstellen und passen Sie Ihre professionellen Visitenkarten an. Teilen Sie sie einfach mit Ihren Kunden und Partnern.",
    "supplier.viewBusinessCardsDesc": "Entdecken Sie die Visitenkarten dieses Lieferanten und laden Sie sie für Ihre Kontakte herunter.",
    "supplier.businessCardsAvailable": "Visitenkarten verfügbar",
    "supplier.supplierSharesCards": "Dieser Lieferant teilt seine Visitenkarten mit Partnern.",
    "supplier.certificationsAndStandards": "Zertifizierungen und Standards",
    "supplier.validCertification": "Gültige Zertifizierung",
    "supplier.companyGallery": "Unternehmensgalerie",
    "supplier.customerReviews": "Kundenbewertungen",
    "supplier.weeksAgo": "vor {{count}} Woche{{count, plural, one {} other {n}}}",
    "supplier.sampleReviewText": "Ausgezeichneter Lieferant! Tadellose Produktqualität und sehr schnelle Lieferung. Ich empfehle sehr.",
    "supplier.helpful": "Hilfreich",
    "supplier.reply": "Antworten",
    "supplier.contactInfo": "Kontaktinformationen",
    "supplier.address": "Adresse",
    "supplier.phone": "Telefon",
    "supplier.email": "E-Mail",
    "supplier.website": "Website",
    "supplier.companyInfo": "Unternehmensinformationen",
    "supplier.foundedIn": "Gegründet in",
    "supplier.employees": "Mitarbeiter",
    "supplier.quickActions": "Schnellaktionen",
    "supplier.sendMessage": "Nachricht senden",
    "supplier.requestQuote": "Angebot anfordern",
    "supplier.downloadCatalog": "Katalog herunterladen",

    // Homepage cards
    "homepage.cards.technology": "Technologie",
    "homepage.cards.electronics": "Elektronik",
    "homepage.cards.electronics.description": "Entdecken Sie die neuesten elektronischen Innovationen",
    "homepage.cards.explore": "Erkunden",
    "homepage.cards.fashion.title": "Mode",
    "homepage.cards.textile": "Textil",
    "homepage.cards.textile.description": "Hochwertige Stoffe für alle Ihre Bedürfnisse",
    "homepage.cards.industrial": "Industrie",
    "homepage.cards.machinery": "Maschinen",
    "homepage.cards.machinery.description": "Hochwertige Industrieausrüstung",
    "homepage.cards.new": "Neu",
    "homepage.cards.decoration": "Dekoration",
    "homepage.cards.home.garden": "Haus und Garten",
    "homepage.cards.home.garden.description": "Verwandeln Sie Ihren Wohnraum",
    "homepage.cards.educational": "Bildung",
    "homepage.cards.toys.children": "Spielzeug und Kinder",
    "homepage.cards.toys.description": "Sichere und lehrreiche Spielzeuge für Kinder",
    "homepage.cards.parts": "Teile",

    // Homepage stats
    "homepage.stats.products": "Produkte",
    "homepage.stats.suppliers": "Lieferanten",
    "homepage.stats.satisfaction": "Zufriedenheit",
    "homepage.stats.response": "Antwort",
    "homepage.categories.popular": "Beliebte Kategorien",
    "homepage.categories.popular.subtitle": "Entdecken Sie unsere gefragtesten Kategorien",
    "homepage.search.placeholder.dev": "🚧 Neue Oberfläche in Entwicklung...",

    "homepage.cards.auto.moto": "Auto und Motorrad",
    "homepage.cards.auto.description": "Autoteile und Zubehör",

    // Homepage sections
    "homepage.categories.section.title": "Nach Kategorien erkunden",
    "homepage.categories.section.subtitle": "Finden Sie schnell, was Sie suchen",
    "homepage.recommendations.loading": "Empfehlungen werden geladen...",
    "homepage.recommendations.badge": "Trends",
    "homepage.recommendations.title": "Für Sie empfohlen",
    "homepage.recommendations.subtitle": "Entdecken Sie unsere personalisierten Auswahlen",
    "homepage.recommendations.viewAll": "Alle anzeigen",
    "homepage.recommendations.discover": "Entdecken",

    // Sourcer Dashboard
    "sourcer.dashboard.title": "Sourcer Dashboard",
    "sourcer.dashboard.description": "Management-Interface für Sourcer.",
    "sourcer.dashboard.comingSoon": "Funktion kommt bald",

    // Homepage benefits
    "homepage.benefits.delivery.title": "Schnelle Lieferung",
    "homepage.benefits.delivery.description": "Versand innerhalb von 24-48h",
    "homepage.benefits.payment.title": "Sichere Zahlung",
    "homepage.benefits.payment.description": "Geschützte und garantierte Transaktionen",
    "homepage.benefits.support.title": "24/7 Support",
    "homepage.benefits.support.description": "Ein engagiertes Team zu Ihren Diensten",

    // Homepage discover
    "homepage.discover.network": "Globales Netzwerk",
    "homepage.discover.title": "Entdecken Sie alle unsere Lieferanten",
    "homepage.discover.highlight": "verifiziert",
    "homepage.discover.subtitle": "Verbinden Sie sich mit über 1000 verifizierten Lieferanten weltweit",
    "homepage.discover.button": "Lieferanten erkunden",
    "homepage.discover.verified": "Über 1000 verifizierte Lieferanten",

    // Common
    "units": "Einheiten",
    "cbm": "CBM",
    "cancel": "Abbrechen",
    "confirm": "Bestätigen",
    "close": "Schließen",

    // --- AJOUT DES CLÉS MANQUANTES POUR LA PAGE D'ACCUEIL DANS TOUTES LES LANGUES ---
    // Pour chaque bloc de langue (fr, en, es, ar, zh, pt, de), je complète les clés manquantes de la page d'accueil
    // Les valeurs sont traduites ou, à défaut, un placeholder est utilisé

    // Exemple pour le bloc espagnol (à placer dans le bloc 'es')
    "homepage.title": "Por traducir",
    "homepage.subtitle": "Por traducir",
    "homepage.subtitle.highlight": "Por traducir",
    "homepage.tagline": "Por traducir",
    "homepage.hero.title": "Por traducir",
    "homepage.hero.subtitle": "Por traducir",
    "homepage.hero.cta": "Por traducir",
    "homepage.cta.title": "Por traducir",
    "homepage.cta.highlight": "Por traducir",
    "homepage.cta.subtitle": "Por traducir",
    "homepage.cta.button": "Por traducir",
    "homepage.final.title": "Por traducir",
    "homepage.final.subtitle": "Por traducir",
    "homepage.final.button": "Por traducir"
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<UserLanguage>('fr');

  const availableLanguages: UserLanguage[] = ['fr', 'en', 'es', 'ar', 'zh', 'pt', 'de'];

  const getLanguageName = useCallback((lang: UserLanguage) => {
    const languageNames: Record<UserLanguage, string> = {
      fr: 'Français',
      en: 'English',
      es: 'Español',
      ar: 'العربية',
      zh: '中文',
      pt: 'Português',
      de: 'Deutsch'
    };
    return languageNames[lang] || lang;
  }, []);

  const t = useCallback((key: string, params?: Record<string, any>) => {
    let translation = translations[currentLanguage]?.[key] || translations.fr[key] || key;

    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        translation = translation.replace(new RegExp(`{{${paramKey}}}`, 'g'), value);
      });
    }

    return translation;
  }, [currentLanguage]);

  const changeLanguage = useCallback((language: UserLanguage) => {
    setCurrentLanguage(language);
  }, []);

  const setLanguage = useCallback((language: UserLanguage) => {
    setCurrentLanguage(language);
  }, []);

  return (
    <LanguageContext.Provider value={{
      language: currentLanguage,
      currentLanguage,
      setLanguage,
      changeLanguage,
      t,
      getLanguageName,
      availableLanguages
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
