import React, { createContext, useState, useContext, useCallback, ReactNode } from 'react';

export type UserLanguage = 'fr' | 'en' | 'es' | 'ar' | 'zh' | 'pt' | 'de';

interface LanguageContextType {
    currentLanguage: UserLanguage;
    changeLanguage: (lang: UserLanguage) => void;
    t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<UserLanguage, Record<string, string>> = {
    fr: {
        "home": "Accueil",
        "search": "Rechercher",
        "search.placeholder": "Rechercher des produits...",
        "dashboard": "Tableau de bord",
        "nav.login": "Connexion",
        "logout": "Déconnexion",
        "discover": "Découvrir",

        // Authentication
        "email": "Email",
        "password": "Mot de passe",
        "confirmPassword": "Confirmer le mot de passe",
        "login": "Connexion",
        "register": "Inscription",
        "loginDescription": "Connectez-vous pour accéder à votre compte",
        "accountType": "Type de compte",
        "role.customer": "Client",
        "role.supplier": "Fournisseur",
        "role.sourcer": "Sourceur",
        "role.influencer": "Influenceur",

        // SupplierProfile Page translations
        "supplier.loadingProfile": "Chargement du profil...",
        "supplier.goldSupplier": "Fournisseur Gold",
        "supplier.reviews": "avis",
        "supplier.since": "Depuis",
        "supplier.contact": "Contact",
        "supplier.viewProducts": "Voir les Produits",
        "supplier.overview": "Aperçu",
        "supplier.products": "Produits",
        "supplier.businessCards": "Cartes de Visite",
        "supplier.certifications": "Certifications",
        "supplier.gallery": "Galerie",
        "supplier.aboutCompany": "À Propos de l'Entreprise",
        "supplier.specialties": "Spécialités",
        "supplier.performance": "Performance",
        "supplier.ordersCompleted": "Commandes Complétées",
        "supplier.responseTime": "Temps de Réponse",
        "supplier.onTimeDelivery": "Livraison à Temps",
        "supplier.viewAll": "Voir Tout",
        "supplier.myBusinessCards": "Mes Cartes de Visite",
        "supplier.createBusinessCardsDesc": "Créez et personnalisez vos cartes de visite professionnelles. Partagez-les facilement avec vos clients et partenaires.",
        "supplier.viewBusinessCardsDesc": "Découvrez les cartes de visite de ce fournisseur et téléchargez-les pour vos contacts.",
        "supplier.businessCardsAvailable": "Cartes de Visite Disponibles",
        "supplier.supplierSharesCards": "Ce fournisseur partage ses cartes de visite avec les partenaires.",
        "supplier.certificationsAndStandards": "Certifications et Normes",
        "supplier.validCertification": "Certification Valide",
        "supplier.companyGallery": "Galerie de l'Entreprise",
        "supplier.customerReviews": "Avis Clients",
        "supplier.weeksAgo": "il y a {{count}} semaine{{count, plural, one {} other {s}}}",
        "supplier.sampleReviewText": "Excellent fournisseur ! Qualité de produit impeccable et livraison très rapide. Je recommande vivement.",
        "supplier.helpful": "Utile",
        "supplier.reply": "Répondre",
        "supplier.contactInfo": "Informations de Contact",
        "supplier.address": "Adresse",
        "supplier.phone": "Téléphone",
        "supplier.email": "Email",
        "supplier.website": "Site Web",
        "supplier.companyInfo": "Informations sur l'Entreprise",
        "supplier.foundedIn": "Fondée en",
        "supplier.employees": "Employés",
        "supplier.quickActions": "Actions Rapides",
        "supplier.sendMessage": "Envoyer un Message",
        "supplier.requestQuote": "Demander un Devis",
        "supplier.downloadCatalog": "Télécharger le Catalogue",

        // Common
        "units": "unités",
        "cbm": "CBM",
        "cancel": "Annuler",
        "confirm": "Confirmer",
        "close": "Fermer"
    },

    en: {
        "home": "Home",
        "search": "Search",
        "search.placeholder": "Search for products...",
        "dashboard": "Dashboard",
        "nav.login": "Login",
        "logout": "Logout",
        "discover": "Discover",

        // Authentication
        "email": "Email",
        "password": "Password",
        "confirmPassword": "Confirm Password",
        "login": "Login",
        "register": "Register",
        "loginDescription": "Sign in to access your account",
        "accountType": "Account Type",
        "role.customer": "Customer",
        "role.supplier": "Supplier",
        "role.sourcer": "Sourcer",
        "role.influencer": "Influencer",

        // SupplierProfile Page translations
        "supplier.loadingProfile": "Loading profile...",
        "supplier.goldSupplier": "Gold Supplier",
        "supplier.reviews": "reviews",
        "supplier.since": "Since",
        "supplier.contact": "Contact",
        "supplier.viewProducts": "View Products",
        "supplier.overview": "Overview",
        "supplier.products": "Products",
        "supplier.businessCards": "Business Cards",
        "supplier.certifications": "Certifications",
        "supplier.gallery": "Gallery",
        "supplier.aboutCompany": "About the Company",
        "supplier.specialties": "Specialties",
        "supplier.performance": "Performance",
        "supplier.ordersCompleted": "Orders Completed",
        "supplier.responseTime": "Response Time",
        "supplier.onTimeDelivery": "On-Time Delivery",
        "supplier.viewAll": "View All",
        "supplier.myBusinessCards": "My Business Cards",
        "supplier.createBusinessCardsDesc": "Create and customize your professional business cards. Share them easily with your clients and partners.",
        "supplier.viewBusinessCardsDesc": "Discover this supplier's business cards and download them for your contacts.",
        "supplier.businessCardsAvailable": "Business Cards Available",
        "supplier.supplierSharesCards": "This supplier shares their business cards with partners.",
        "supplier.certificationsAndStandards": "Certifications and Standards",
        "supplier.validCertification": "Valid Certification",
        "supplier.companyGallery": "Company Gallery",
        "supplier.customerReviews": "Customer Reviews",
        "supplier.weeksAgo": "{{count}} week{{count, plural, one {} other {s}}} ago",
        "supplier.sampleReviewText": "Excellent supplier! Impeccable product quality and very fast delivery. I highly recommend.",
        "supplier.helpful": "Helpful",
        "supplier.reply": "Reply",
        "supplier.contactInfo": "Contact Information",
        "supplier.address": "Address",
        "supplier.phone": "Phone",
        "supplier.email": "Email",
        "supplier.website": "Website",
        "supplier.companyInfo": "Company Information",
        "supplier.foundedIn": "Founded in",
        "supplier.employees": "Employees",
        "supplier.quickActions": "Quick Actions",
        "supplier.sendMessage": "Send Message",
        "supplier.requestQuote": "Request Quote",
        "supplier.downloadCatalog": "Download Catalog",

        // Common
        "units": "units",
        "cbm": "CBM",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "close": "Close"
    },

    es: {
        "home": "Inicio",
        "search": "Buscar",
        "search.placeholder": "Buscar productos...",
        "dashboard": "Panel",
        "nav.login": "Iniciar Sesión",
        "logout": "Cerrar Sesión",
        "discover": "Descubrir",

        // Authentication
        "email": "Email",
        "password": "Contraseña",
        "confirmPassword": "Confirmar Contraseña",
        "login": "Iniciar Sesión",
        "register": "Registrarse",
        "loginDescription": "Inicia sesión para acceder a tu cuenta",
        "accountType": "Tipo de Cuenta",
        "role.customer": "Cliente",
        "role.supplier": "Proveedor",
        "role.sourcer": "Buscador",
        "role.influencer": "Influencer",

        // SupplierProfile Page translations
        "supplier.loadingProfile": "Cargando perfil...",
        "supplier.goldSupplier": "Proveedor de Oro",
        "supplier.reviews": "reseñas",
        "supplier.since": "Desde",
        "supplier.contact": "Contacto",
        "supplier.viewProducts": "Ver Productos",
        "supplier.overview": "Resumen",
        "supplier.products": "Productos",
        "supplier.businessCards": "Tarjetas de Negocio",
        "supplier.certifications": "Certificaciones",
        "supplier.gallery": "Galería",
        "supplier.aboutCompany": "Acerca de la Empresa",
        "supplier.specialties": "Especialidades",
        "supplier.performance": "Rendimiento",
        "supplier.ordersCompleted": "Pedidos Completados",
        "supplier.responseTime": "Tiempo de Respuesta",
        "supplier.onTimeDelivery": "Entrega a Tiempo",
        "supplier.viewAll": "Ver Todo",
        "supplier.myBusinessCards": "Mis Tarjetas de Negocio",
        "supplier.createBusinessCardsDesc": "Crea y personaliza tus tarjetas de negocio profesionales. Compártelas fácilmente con tus clientes y socios.",
        "supplier.viewBusinessCardsDesc": "Descubre las tarjetas de negocio de este proveedor y descárgalas para tus contactos.",
        "supplier.businessCardsAvailable": "Tarjetas de Negocio Disponibles",
        "supplier.supplierSharesCards": "Este proveedor comparte sus tarjetas de negocio con socios.",
        "supplier.certificationsAndStandards": "Certificaciones y Estándares",
        "supplier.validCertification": "Certificación Válida",
        "supplier.companyGallery": "Galería de la Empresa",
        "supplier.customerReviews": "Reseñas de Clientes",
        "supplier.weeksAgo": "hace {{count}} semana{{count, plural, one {} other {s}}}",
        "supplier.sampleReviewText": "¡Excelente proveedor! Calidad de producto impecable y entrega muy rápida. Lo recomiendo mucho.",
        "supplier.helpful": "Útil",
        "supplier.reply": "Responder",
        "supplier.contactInfo": "Información de Contacto",
        "supplier.address": "Dirección",
        "supplier.phone": "Teléfono",
        "supplier.email": "Email",
        "supplier.website": "Sitio Web",
        "supplier.companyInfo": "Información de la Empresa",
        "supplier.foundedIn": "Fundada en",
        "supplier.employees": "Empleados",
        "supplier.quickActions": "Acciones Rápidas",
        "supplier.sendMessage": "Enviar Mensaje",
        "supplier.requestQuote": "Solicitar Cotización",
        "supplier.downloadCatalog": "Descargar Catálogo",

        // Common
        "units": "unidades",
        "cbm": "CBM",
        "cancel": "Cancelar",
        "confirm": "Confirmar",
        "close": "Cerrar"
    },

    ar: {
        "home": "الرئيسية",
        "search": "بحث",
        "search.placeholder": "البحث عن المنتجات...",
        "dashboard": "لوحة القيادة",
        "nav.login": "تسجيل الدخول",
        "logout": "تسجيل الخروج",
        "discover": "اكتشف",

        // Authentication
        "email": "البريد الإلكتروني",
        "password": "كلمة المرور",
        "confirmPassword": "تأكيد كلمة المرور",
        "login": "تسجيل الدخول",
        "register": "التسجيل",
        "loginDescription": "قم بتسجيل الدخول للوصول إلى حسابك",
        "accountType": "نوع الحساب",
        "role.customer": "عميل",
        "role.supplier": "مورد",
        "role.sourcer": "باحث",
        "role.influencer": "مؤثر",

        // SupplierProfile Page translations
        "supplier.loadingProfile": "جاري تحميل الملف الشخصي...",
        "supplier.goldSupplier": "مورد ذهبي",
        "supplier.reviews": "مراجعات",
        "supplier.since": "منذ",
        "supplier.contact": "اتصال",
        "supplier.viewProducts": "عرض المنتجات",
        "supplier.overview": "نظرة عامة",
        "supplier.products": "المنتجات",
        "supplier.businessCards": "بطاقات العمل",
        "supplier.certifications": "الشهادات",
        "supplier.gallery": "المعرض",
        "supplier.aboutCompany": "حول الشركة",
        "supplier.specialties": "التخصصات",
        "supplier.performance": "الأداء",
        "supplier.ordersCompleted": "الطلبات المكتملة",
        "supplier.responseTime": "وقت الاستجابة",
        "supplier.onTimeDelivery": "التسليم في الوقت المحدد",
        "supplier.viewAll": "عرض الكل",
        "supplier.myBusinessCards": "بطاقات العمل الخاصة بي",
        "supplier.createBusinessCardsDesc": "أنشئ وخصص بطاقات العمل المهنية الخاصة بك. شاركها بسهولة مع عملائك وشركائك.",
        "supplier.viewBusinessCardsDesc": "اكتشف بطاقات عمل هذا المورد وحملها لجهات الاتصال الخاصة بك.",
        "supplier.businessCardsAvailable": "بطاقات العمل متاحة",
        "supplier.supplierSharesCards": "يشارك هذا المورد بطاقات عمله مع الشركاء.",
        "supplier.certificationsAndStandards": "الشهادات والمعايير",
        "supplier.validCertification": "شهادة صالحة",
        "supplier.companyGallery": "معرض الشركة",
        "supplier.customerReviews": "مراجعات العملاء",
        "supplier.weeksAgo": "منذ {{count}} أسبوع{{count, plural, one {} other {}}}",
        "supplier.sampleReviewText": "مورد ممتاز! جودة منتج لا تشوبها شائبة وتسليم سريع جداً. أنصح بشدة.",
        "supplier.helpful": "مفيد",
        "supplier.reply": "رد",
        "supplier.contactInfo": "معلومات الاتصال",
        "supplier.address": "العنوان",
        "supplier.phone": "الهاتف",
        "supplier.email": "البريد الإلكتروني",
        "supplier.website": "الموقع الإلكتروني",
        "supplier.companyInfo": "معلومات الشركة",
        "supplier.foundedIn": "تأسست في",
        "supplier.employees": "الموظفون",
        "supplier.quickActions": "إجراءات سريعة",
        "supplier.sendMessage": "إرسال رسالة",
        "supplier.requestQuote": "طلب عرض أسعار",
        "supplier.downloadCatalog": "تنزيل الكتالوج",

        // Common
        "units": "وحدات",
        "cbm": "CBM",
        "cancel": "إلغاء",
        "confirm": "تأكيد",
        "close": "إغلاق"
    },

    zh: {
        "home": "首页",
        "search": "搜索",
        "search.placeholder": "搜索产品...",
        "dashboard": "仪表板",
        "nav.login": "登录",
        "logout": "退出",
        "discover": "发现",

        // Authentication
        "email": "邮箱",
        "password": "密码",
        "confirmPassword": "确认密码",
        "login": "登录",
        "register": "注册",
        "loginDescription": "登录以访问您的账户",
        "accountType": "账户类型",
        "role.customer": "客户",
        "role.supplier": "供应商",
        "role.sourcer": "采购商",
        "role.influencer": "影响者",

        // SupplierProfile Page translations
        "supplier.loadingProfile": "正在加载档案...",
        "supplier.goldSupplier": "金牌供应商",
        "supplier.reviews": "评价",
        "supplier.since": "自从",
        "supplier.contact": "联系",
        "supplier.viewProducts": "查看产品",
        "supplier.overview": "概览",
        "supplier.products": "产品",
        "supplier.businessCards": "名片",
        "supplier.certifications": "认证",
        "supplier.gallery": "画廊",
        "supplier.aboutCompany": "关于公司",
        "supplier.specialties": "专业",
        "supplier.performance": "业绩",
        "supplier.ordersCompleted": "已完成订单",
        "supplier.responseTime": "响应时间",
        "supplier.onTimeDelivery": "按时交付",
        "supplier.viewAll": "查看全部",
        "supplier.myBusinessCards": "我的名片",
        "supplier.createBusinessCardsDesc": "创建和自定义您的专业名片。轻松与您的客户和合作伙伴分享。",
        "supplier.viewBusinessCardsDesc": "发现此供应商的名片并下载到您的联系人。",
        "supplier.businessCardsAvailable": "可用名片",
        "supplier.supplierSharesCards": "此供应商与合作伙伴分享名片。",
        "supplier.certificationsAndStandards": "认证和标准",
        "supplier.validCertification": "有效认证",
        "supplier.companyGallery": "公司画廊",
        "supplier.customerReviews": "客户评价",
        "supplier.weeksAgo": "{{count}}周前",
        "supplier.sampleReviewText": "优秀的供应商！产品质量完美，交付非常快。我强烈推荐。",
        "supplier.helpful": "有用",
        "supplier.reply": "回复",
        "supplier.contactInfo": "联系信息",
        "supplier.address": "地址",
        "supplier.phone": "电话",
        "supplier.email": "邮箱",
        "supplier.website": "网站",
        "supplier.companyInfo": "公司信息",
        "supplier.foundedIn": "成立于",
        "supplier.employees": "员工",
        "supplier.quickActions": "快速操作",
        "supplier.sendMessage": "发送消息",
        "supplier.requestQuote": "请求报价",
        "supplier.downloadCatalog": "下载目录",

        // Common
        "units": "单位",
        "cbm": "CBM",
        "cancel": "取消",
        "confirm": "确认",
        "close": "关闭"
    },

    pt: {
        "home": "Início",
        "search": "Pesquisar",
        "search.placeholder": "Pesquisar produtos...",
        "dashboard": "Painel",
        "nav.login": "Entrar",
        "logout": "Sair",
        "discover": "Descobrir",

        // Authentication
        "email": "Email",
        "password": "Senha",
        "confirmPassword": "Confirmar Senha",
        "login": "Entrar",
        "register": "Registrar",
        "loginDescription": "Entre para acessar sua conta",
        "accountType": "Tipo de Conta",
        "role.customer": "Cliente",
        "role.supplier": "Fornecedor",
        "role.sourcer": "Sourcer",
        "role.influencer": "Influenciador",

        // SupplierProfile Page translations
        "supplier.loadingProfile": "Carregando perfil...",
        "supplier.goldSupplier": "Fornecedor Gold",
        "supplier.reviews": "avaliações",
        "supplier.since": "Desde",
        "supplier.contact": "Contato",
        "supplier.viewProducts": "Ver Produtos",
        "supplier.overview": "Visão Geral",
        "supplier.products": "Produtos",
        "supplier.businessCards": "Cartões de Visita",
        "supplier.certifications": "Certificações",
        "supplier.gallery": "Galeria",
        "supplier.aboutCompany": "Sobre a Empresa",
        "supplier.specialties": "Especialidades",
        "supplier.performance": "Desempenho",
        "supplier.ordersCompleted": "Pedidos Concluídos",
        "supplier.responseTime": "Tempo de Resposta",
        "supplier.onTimeDelivery": "Entrega Pontual",
        "supplier.viewAll": "Ver Tudo",
        "supplier.myBusinessCards": "Meus Cartões de Visita",
        "supplier.createBusinessCardsDesc": "Crie e personalize seus cartões de visita profissionais. Compartilhe facilmente com seus clientes e parceiros.",
        "supplier.viewBusinessCardsDesc": "Descubra os cartões de visita deste fornecedor e baixe para seus contatos.",
        "supplier.businessCardsAvailable": "Cartões de Visita Disponíveis",
        "supplier.supplierSharesCards": "Este fornecedor compartilha cartões de visita com parceiros.",
        "supplier.certificationsAndStandards": "Certificações e Padrões",
        "supplier.validCertification": "Certificação Válida",
        "supplier.companyGallery": "Galeria da Empresa",
        "supplier.customerReviews": "Avaliações de Clientes",
        "supplier.weeksAgo": "{{count}} semana{{count, plural, one {} other {s}}} atrás",
        "supplier.sampleReviewText": "Excelente fornecedor! Qualidade do produto impecável e entrega muito rápida. Recomendo muito.",
        "supplier.helpful": "Útil",
        "supplier.reply": "Responder",
        "supplier.contactInfo": "Informações de Contato",
        "supplier.address": "Endereço",
        "supplier.phone": "Telefone",
        "supplier.email": "Email",
        "supplier.website": "Site",
        "supplier.companyInfo": "Informações da Empresa",
        "supplier.foundedIn": "Fundada em",
        "supplier.employees": "Funcionários",
        "supplier.quickActions": "Ações Rápidas",
        "supplier.sendMessage": "Enviar Mensagem",
        "supplier.requestQuote": "Solicitar Cotação",
        "supplier.downloadCatalog": "Baixar Catálogo",

        // Common
        "units": "unidades",
        "cbm": "CBM",
        "cancel": "Cancelar",
        "confirm": "Confirmar",
        "close": "Fechar"
    },

    de: {
        "home": "Startseite",
        "search": "Suchen",
        "search.placeholder": "Produkte suchen...",
        "dashboard": "Dashboard",
        "nav.login": "Anmelden",
        "logout": "Abmelden",
        "discover": "Entdecken",

        // Authentication
        "email": "E-Mail",
        "password": "Passwort",
        "confirmPassword": "Passwort bestätigen",
        "login": "Anmelden",
        "register": "Registrieren",
        "loginDescription": "Melden Sie sich an, um auf Ihr Konto zuzugreifen",
        "accountType": "Kontotyp",
        "role.customer": "Kunde",
        "role.supplier": "Lieferant",
        "role.sourcer": "Beschaffer",
        "role.influencer": "Influencer",

        // SupplierProfile Page translations
        "supplier.loadingProfile": "Profil wird geladen...",
        "supplier.goldSupplier": "Gold-Lieferant",
        "supplier.reviews": "Bewertungen",
        "supplier.since": "Seit",
        "supplier.contact": "Kontakt",
        "supplier.viewProducts": "Produkte anzeigen",
        "supplier.overview": "Übersicht",
        "supplier.products": "Produkte",
        "supplier.businessCards": "Visitenkarten",
        "supplier.certifications": "Zertifizierungen",
        "supplier.gallery": "Galerie",
        "supplier.aboutCompany": "Über das Unternehmen",
        "supplier.specialties": "Spezialitäten",
        "supplier.performance": "Leistung",
        "supplier.ordersCompleted": "Abgeschlossene Bestellungen",
        "supplier.responseTime": "Antwortzeit",
        "supplier.onTimeDelivery": "Pünktliche Lieferung",
        "supplier.viewAll": "Alle anzeigen",
        "supplier.myBusinessCards": "Meine Visitenkarten",
        "supplier.createBusinessCardsDesc": "Erstellen und passen Sie Ihre professionellen Visitenkarten an. Teilen Sie sie einfach mit Ihren Kunden und Partnern.",
        "supplier.viewBusinessCardsDesc": "Entdecken Sie die Visitenkarten dieses Lieferanten und laden Sie sie für Ihre Kontakte herunter.",
        "supplier.businessCardsAvailable": "Visitenkarten verfügbar",
        "supplier.supplierSharesCards": "Dieser Lieferant teilt seine Visitenkarten mit Partnern.",
        "supplier.certificationsAndStandards": "Zertifizierungen und Standards",
        "supplier.validCertification": "Gültige Zertifizierung",
        "supplier.companyGallery": "Unternehmensgalerie",
        "supplier.customerReviews": "Kundenbewertungen",
        "supplier.weeksAgo": "vor {{count}} Woche{{count, plural, one {} other {n}}}",
        "supplier.sampleReviewText": "Ausgezeichneter Lieferant! Tadellose Produktqualität und sehr schnelle Lieferung. Ich empfehle sehr.",
        "supplier.helpful": "Hilfreich",
        "supplier.reply": "Antworten",
        "supplier.contactInfo": "Kontaktinformationen",
        "supplier.address": "Adresse",
        "supplier.phone": "Telefon",
        "supplier.email": "E-Mail",
        "supplier.website": "Website",
        "supplier.companyInfo": "Unternehmensinformationen",
        "supplier.foundedIn": "Gegründet in",
        "supplier.employees": "Mitarbeiter",
        "supplier.quickActions": "Schnellaktionen",
        "supplier.sendMessage": "Nachricht senden",
        "supplier.requestQuote": "Angebot anfordern",
        "supplier.downloadCatalog": "Katalog herunterladen",

        // Common
        "units": "Einheiten",
        "cbm": "CBM",
        "cancel": "Abbrechen",
        "confirm": "Bestätigen",
        "close": "Schließen"
    }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [currentLanguage, setCurrentLanguage] = useState<UserLanguage>('fr');

    const t = useCallback((key: string, params?: Record<string, any>) => {
        let translation = translations[currentLanguage]?.[key] || translations.fr[key] || key;

        if (params) {
            Object.entries(params).forEach(([paramKey, value]) => {
                translation = translation.replace(new RegExp(`{{${paramKey}}}`, 'g'), value);
            });
        }

        return translation;
    }, [currentLanguage]);

    const changeLanguage = useCallback((language: UserLanguage) => {
        setCurrentLanguage(language);
    }, []);

    return (
        <LanguageContext.Provider value={{ currentLanguage, changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
