import React, { createContext, useState, useContext, useEffect } from 'react';
import { useAuth } from './AuthContext';

export type UserLanguage = 'fr' | 'en' | 'es' | 'ar' | 'zh' | 'pt' | 'nl';

interface LanguageContextType {
  language: UserLanguage;
  setLanguage: (lang: UserLanguage) => void;
  t: (key: string, params?: Record<string, any>) => string;
  availableLanguages: UserLanguage[];
  getLanguageName: (lang: UserLanguage) => string;
}

const translations: Record<UserLanguage, Record<string, string>> = {
  "fr": {
    "home": "Accueil",
    "search": "Rechercher",
    "search.placeholder": "Rechercher des produits...",
    "dashboard": "Tableau de bord",
    "nav.login": "Connexion",
    "logout": "Déconnexion",
    "discover": "Découvrir",

    "notifications.title": "Notifications",
    "notifications.noNotifications": "Aucune notification",
    "notifications.noNotificationsMessage": "Vous n'avez aucune notification pour le moment",
    "notifications.markAllAsRead": "Tout marquer comme lu",
    "notifications.markAsRead": "Marquer comme lu",
    "notifications.refresh": "Actualiser",
    "notifications.filters": "Filtres",
    "notifications.status": "Statut",
    "notifications.type": "Type",
    "notifications.all": "Tous",
    "notifications.unread": "Non lus",
    "notifications.read": "Lus",
    "notifications.allTypes": "Tous les types",
    "notifications.orders": "Commandes",
    "notifications.payments": "Paiements",
    "notifications.shipments": "Expéditions",
    "notifications.system": "Système",
    "notifications.info": "Information",
    "notifications.warnings": "Avertissements",
    "notifications.errors": "Erreurs",
    "notifications.clearFilters": "Effacer",
    "notifications.loading": "Chargement...",
    "notifications.error": "Erreur lors du chargement des notifications",
    "notifications.seeDetails": "Voir les détails",
    "notifications.timeAgo.now": "À l'instant",
    "notifications.timeAgo.minutes": "Il y a {0} min",
    "notifications.timeAgo.hours": "Il y a {0}h",
    "notifications.timeAgo.days": "Il y a {0}j",
    "notifications.priority.urgent": "Urgent",
    "notifications.priority.high": "Élevé",
    "notifications.priority.medium": "Moyen",
    "notifications.priority.low": "Faible",
    "notifications.allLoaded": "Toutes les notifications ont été chargées",
    "notifications.count.singular": "{0} non lu",
    "notifications.count.plural": "{0} non lus",

    "email": "Email",
    "password": "Mot de passe",
    "confirmPassword": "Confirmer le mot de passe",
    "login": "Connexion",
    "register": "Inscription",
    "loginDescription": "Connectez-vous pour accéder à votre compte",
    "accountType": "Type de compte",
    "role.customer": "Client",
    "role.supplier": "Fournisseur",
    "role.sourcer": "Sourceur",
    "role.influencer": "Influenceur",
    "emailPlaceholder": "votre@email.com",
    "passwordPlaceholder": "••••••••",
    "rememberMe": "Se souvenir de moi",
    "forgotPassword": "Mot de passe oublié ?",
    "loginButton": "Se connecter",
    "loggingIn": "Connexion...",
    "createAccount": "Créer un compte",
    "registerDescription": "Créez votre compte pour commencer",
    "fullName": "Nom complet",
    "yourNamePlaceholder": "Votre nom complet",
    "nameRequired": "Le nom est requis",
    "emailRequired": "L'email est requis",
    "passwordMinLength": "Le mot de passe doit contenir au moins 6 caractères",
    "passwordsDoNotMatch": "Les mots de passe ne correspondent pas",
    "registrationError": "Erreur d'inscription",
    "creatingAccount": "Création du compte...",
    "createMyAccount": "Créer mon compte",
    "hasAccountQuestion": "Vous avez déjà un compte ?",
    "role.customerTitle": "Client",
    "role.supplierTitle": "Fournisseur",
    "role.sourcerTitle": "Sourceur",
    "role.customerDescription": "Acheter des produits aux fournisseurs",
    "role.supplierDescription": "Vendre vos produits aux clients",
    "role.sourcerDescription": "Aider les clients à trouver les meilleurs fournisseurs",
    "common.optional": "Optionnel",
    "fashion": "Mode",
    "tech": "Technologie",
    "beauty": "Beauté",
    "sports": "Sport",
    "mainAudience": "Audience principale",
    "mainAudiencePlaceholder": "Pays ou région majoritaire, âge moyen",
    "engagementRate": "Taux d'engagement",
    "engagementRatePlaceholder": "Facultatif, utile pour évaluer l'interaction",
    "shareStatsAgreement": "J'accepte de partager mes statistiques détaillées sur demande",
    "mediaKit": "Kit média",
    "message": "Message",
    "messagePlaceholder": "Présentez-vous brièvement",
    "socialMediaLinks": "Liens vers les réseaux sociaux",
    "socialMediaLinksPlaceholder": "Instagram, TikTok, YouTube, etc.",
    "followerCount": "Nombre de followers",
    "followerCountPlaceholder": "Nombre de followers pour chaque réseau",
    "category": "Catégorie d'influence",

    "emptyFields": "Veuillez remplir tous les champs",
    "loginError": "Erreur de connexion",
    "loginErrorTitle": "Erreur de connexion",
    "registerNow": "S'inscrire maintenant",
    "noAccountQuestion": "Pas encore de compte ?",

    "termsAgreement": "En continuant, vous acceptez nos conditions d'utilisation et notre politique de confidentialité.",
    "termsOfUse": "conditions d'utilisation",
    "privacyPolicy": "politique de confidentialité",
    "welcomeBack": "Bon retour !",
    "joinUs": "Rejoignez-nous",
    "loginSubtitle": "Connectez-vous pour accéder à votre espace et découvrir les dernières opportunités commerciales",
    "registerSubtitle": "Créez votre compte et découvrez toutes les opportunités d'affaires avec la Chine",
    "signIn": "Se connecter",
    "signUp": "S'inscrire",
    "signInSubtitle": "Accédez à votre espace personnel",
    "signUpSubtitle": "Créez votre compte en quelques étapes",
    "googleLoginError": "Erreur de connexion Google",
    "orContinueWith": "Ou continuer avec",
    "signInWithGoogle": "Continuer avec Google",
    "agreementPrefix": "En continuant, vous acceptez nos",
    "agreementSuffix": ".",
    "and": "et",
    "andOur": "et notre",
    "termsOfService": "conditions d'utilisation",
    "loginNow": "Se connecter maintenant",
    "welcome.back": "Bon retour !",
    "welcome.back.subtitle": "Connectez-vous pour accéder à votre espace et découvrir les dernières opportunités commerciales avec la Chine.",
    "welcome.join": "Rejoignez-nous !",
    "welcome.join.subtitle": "Créez votre compte et découvrez toutes les opportunités d'affaires avec la Chine",
    "registrationErrorTitle": "Erreur d'inscription",
    "search.button": "Rechercher",

    "socialNetworkSelector.title": "Réseaux sociaux",
    "socialNetworkSelector.subtitle": "Sélectionnez vos réseaux sociaux",
    "socialNetworkSelector.modalInfo": "Un formulaire s'ouvrira pour renseigner vos liens",
    "socialNetworks.instagram": "Instagram",
    "socialNetworks.tiktok": "TikTok",
    "socialNetworks.youtube": "YouTube",
    "socialNetworks.twitter": "X (Twitter)",
    "socialNetworks.linkedin": "LinkedIn",
    "socialNetworks.facebook": "Facebook",
    "socialNetworks.twitch": "Twitch",
    "socialMediaModal.title": "Liens de vos profils",
    "socialMediaModal.description": "Veuillez renseigner les liens de vos profils pour chaque réseau social sélectionné :",
    "socialMediaModal.linkFor": "Lien de votre profil",
    "socialMediaModal.urlRequired": "Ce champ est obligatoire",
    "socialMediaModal.invalidUrl": "Veuillez entrer une URL valide",
    "socialMediaModal.invalidDomain": "L'URL doit contenir le bon domaine",
    "socialMediaModal.close": "Fermer",
    "socialMediaModal.cancel": "Annuler",
    "socialMediaModal.save": "Valider",
    "socialMediaValidation.noNetworkSelected": "Veuillez sélectionner au moins un réseau social",
    "socialMediaValidation.noLinksProvided": "Veuillez renseigner les liens de vos profils",

    "homepage.title": "Chine ton usine",
    "homepage.subtitle": "ÇA VA VOUS",
    "homepage.subtitle.highlight": "PLAIRE",
    "homepage.tagline": "Coup de foudre inévitable.",
    "homepage.search.placeholder": "Recherchez un produit, une marque...",
    "homepage.recommendations.badge": "Recommandé",
    "homepage.recommendations.title": "Produits recommandés pour vous",
    "homepage.recommendations.subtitle": "Découvrez notre sélection personnalisée de produits",
    "homepage.recommendations.viewAll": "Voir tout",
    "homepage.recommendations.discover": "Découvrir",

    "homepage.categories.home": "Accueil",
    "homepage.categories.electronics": "Électronique",
    "homepage.categories.fashion": "Mode",
    "homepage.categories.home.category": "Maison",
    "homepage.categories.beauty": "Beauté",
    "homepage.categories.sports": "Sport",
    "homepage.categories.automotive": "Auto",
    "homepage.categories.tools": "Outils",
    "homepage.categories.toys": "Jouets",
    "homepage.categories.books": "Livres",
    "homepage.categories.music": "Musique",
    "homepage.categories.garden": "Jardin",

    "homepage.network.badge": "Réseau global",
    "homepage.network.suppliers": "Plus de 1000 fournisseurs vérifiés",

    "homepage.cards.technology": "TECHNOLOGIE",
    "homepage.cards.electronics": "ÉLECTRONIQUE",
    "homepage.cards.electronics.description": "Composants & Gadgets",
    "homepage.cards.explore": "Explorer",
    "homepage.cards.fashion.title": "MODE & VÊTEMENTS",
    "homepage.cards.textile": "TEXTILE",
    "homepage.cards.textile.description": "Fabrication Premium",
    "homepage.cards.industrial": "ÉQUIPEMENT INDUSTRIEL",
    "homepage.cards.machinery": "MACHINERIE",
    "homepage.cards.machinery.description": "Performance & Innovation",
    "homepage.cards.decoration": "DÉCORATION & MOBILIER",
    "homepage.cards.home.garden": "MAISON & JARDIN",
    "homepage.cards.home.garden.description": "Design & Confort",
    "homepage.cards.new": "Nouveau",
    "homepage.cards.educational": "ÉDUCATIF & LUDIQUE",
    "homepage.cards.toys.children": "JOUETS & ENFANTS",
    "homepage.cards.toys.description": "Qualité Certifiée",
    "homepage.cards.parts": "PIÈCES & ACCESSOIRES",
    "homepage.cards.auto.moto": "AUTO & MOTO",
    "homepage.cards.auto.description": "Pièces de Qualité",

    "homepage.cta.title": "ÇA VA VOUS",
    "homepage.cta.highlight": "PLAIRE",
    "homepage.cta.subtitle": "Coup de foudre inévitable.",
    "homepage.cta.button": "Découvrir tous les fournisseurs",

    "homepage.how.title": "Comment ça marche ?",
    "homepage.how.subtitle": "Trouvez votre usine en Chine en seulement 3 étapes",
    "homepage.how.step1.title": "1. Recherchez vos produits",
    "homepage.how.step1.description": "Utilisez nos filtres avancés pour trouver exactement ce que vous cherchez parmi des millions de produits.",
    "homepage.how.step2.title": "2. Contactez les fournisseurs",
    "homepage.how.step2.description": "Entrez en contact direct avec des usines chinoises vérifiées et fiables, sans intermédiaire.",
    "homepage.how.step3.title": "3. Commandez et importez",
    "homepage.how.step3.description": "Négociez vos prix, obtenez des échantillons et lancez votre commande en toute sérénité.",
    "homepage.how.cta": "Créer un compte",

    "homepage.discover.title": "DÉCOUVREZ TOUS NOS",
    "homepage.discover.highlight": "FOURNISSEURS",
    "homepage.discover.subtitle": "Des milliers de fournisseurs vérifiés vous attendent.",
    "homepage.discover.button": "Découvrir tous les fournisseurs",

    "homepage.process.title": "Comment ça marche ?",
    "homepage.process.subtitle": "Notre plateforme vous connecte directement avec les meilleurs fournisseurs chinois",
    "homepage.process.step1.title": "1. Explorez",
    "homepage.process.step1.description": "Parcourez notre catalogue de milliers de produits et fournisseurs vérifiés selon vos besoins.",
    "homepage.process.step2.title": "2. Comparez",
    "homepage.process.step2.description": "Évaluez les prix, la qualité, les certifications et les avis pour choisir le meilleur fournisseur.",
    "homepage.process.step3.title": "3. Contactez",
    "homepage.process.step3.description": "Échangez directement avec les fournisseurs pour négocier les prix et demander des échantillons.",
    "homepage.process.step4.title": "4. Commandez",
    "homepage.process.step4.description": "Finalisez votre commande en toute sécurité avec notre système de paiement protégé.",
    "homepage.process.cta": "Commencer maintenant",

    "homepage.optimize.title": "Optimisez votre processus d'achat",
    "homepage.optimize.search.title": "Recherchez efficacement",
    "homepage.optimize.search.description": "Trouvez rapidement les produits que vous cherchez grâce à nos filtres avancés",
    "homepage.optimize.identify.title": "Identifiez les meilleurs fournisseurs",
    "homepage.optimize.identify.description": "Comparez les fournisseurs selon vos critères de qualité et de prix",
    "homepage.optimize.pay.title": "Payez en sécurité",
    "homepage.optimize.pay.description": "Effectuez vos paiements en toute confiance avec notre système sécurisé",
    "homepage.optimize.manage.title": "Gérez vos commandes",
    "homepage.optimize.manage.description": "Suivez l'état de vos commandes en temps réel depuis votre tableau de bord",

    "homepage.final.title": "Prêt à développer votre business ?",
    "homepage.final.subtitle": "Commencez à importer depuis la Chine dès aujourd'hui.",
    "homepage.final.button": "Créer un compte gratuitement",

    "supplier.sidebar.title": "ChineTonUsine",
    "supplier.sidebar.dashboard": "Tableau de bord",
    "supplier.sidebar.products": "Produits",
    "supplier.sidebar.customers": "Clients",
    "supplier.sidebar.messages": "Messages",
    "supplier.sidebar.documents": "Documents",
    "supplier.sidebar.reviews": "Avis",
    "supplier.sidebar.analytics": "Analyses",
    "supplier.sidebar.settings": "Paramètres",
    "supplier.companyName": "Nom de l'entreprise",
    "supplier.legalRegistrationNumber": "Numéro d'enregistrement légal",
    "supplier.website": "Site web (optionnel)",
    "supplier.productCategory": "Catégorie de produits",
    "supplier.categories.textile": "Textile",
    "supplier.categories.electronics": "Électronique",
    "supplier.categories.food": "Agroalimentaire",
    "supplier.categories.machinery": "Machines",
    "supplier.categories.automotive": "Automobile",
    "supplier.categories.beauty": "Beauté",
    "supplier.categories.homeGarden": "Maison et jardin",
    "supplier.categories.toys": "Jouets",
    "supplier.categories.industrial": "Industriel",
    "supplier.categories.other": "Autre",
    "supplier.monthlyProductionCapacity": "Capacité de production mensuelle",
    "supplier.productionCountryRegion": "Pays et région de production",
    "supplier.certifications": "Certifications (ISO, CE, etc.)",
    "supplier.qualityControlMethods": "Méthodes de contrôle qualité",
    "supplier.presentationVideo": "Vidéo de présentation ou lien YouTube (optionnel)",
    "supplier.companyMessage": "Message de présentation de l'entreprise",
    "supplier.documents": "Documents de l'entreprise (certificats, catalogues, etc.)",
    "supplier.agreeToVerification": "J'accepte que mes informations soient vérifiées",
    "supplier.registration.message": "Vous serez contacté pour finaliser votre inscription fournisseur",
    "supplier.registration.validation": "Votre compte sera validé manuellement par notre équipe",
    "supplier.registration.title": "Information Importante",
    "supplier.registration.submitButton": "Soumettre la demande",
    
    // SupplierProfile Page translations
    "supplier.loadingProfile": "Loading profile...",
    "supplier.goldSupplier": "Gold Supplier",
    "supplier.reviews": "reviews",
    "supplier.since": "Since",
    "supplier.contact": "Contact",
    "supplier.viewProducts": "View Products",
    "supplier.overview": "Overview",
    "supplier.products": "Products",
    "supplier.businessCards": "Business Cards",
    "supplier.certifications": "Certifications",
    "supplier.gallery": "Gallery",
    "supplier.aboutCompany": "About the Company",
    "supplier.specialties": "Specialties",
    "supplier.performance": "Performance",
    "supplier.ordersCompleted": "Orders Completed",
    "supplier.responseTime": "Response Time",
    "supplier.onTimeDelivery": "On-Time Delivery",
    "supplier.viewAll": "View All",
    "supplier.myBusinessCards": "My Business Cards",
    "supplier.createBusinessCardsDesc": "Create and customize your professional business cards. Share them easily with your clients and partners.",
    "supplier.viewBusinessCardsDesc": "Discover this supplier's business cards and download them for your contacts.",
    "supplier.businessCardsAvailable": "Business Cards Available",
    "supplier.supplierSharesCards": "This supplier shares their business cards with partners.",
    "supplier.certificationsAndStandards": "Certifications and Standards",
    "supplier.validCertification": "Valid Certification",
    "supplier.companyGallery": "Company Gallery",
    "supplier.customerReviews": "Customer Reviews",
    "supplier.weeksAgo": "{{count}} week{{count, plural, one {} other {s}}} ago",
    "supplier.sampleReviewText": "Excellent supplier! Impeccable product quality and very fast delivery. I highly recommend.",
    "supplier.helpful": "Helpful",
    "supplier.reply": "Reply",
    "supplier.contactInfo": "Contact Information",
    "supplier.address": "Address",
    "supplier.phone": "Phone",
    "supplier.email": "Email",
    "supplier.website": "Website",
    "supplier.companyInfo": "Company Information",
    "supplier.foundedIn": "Founded in",
    "supplier.employees": "Employees",
    "supplier.quickActions": "Quick Actions",
    "supplier.sendMessage": "Send Message",
    "supplier.requestQuote": "Request Quote",
    "supplier.downloadCatalog": "Download Catalog",
    
    "sourcer.registration.message": "You will be contacted to finalize your sourcer registration",
    "fileUpload.dragDrop": "Glissez et déposez un fichier ici",
    "fileUpload.orClick": "ou cliquez pour sélectionner",
    "fileUpload.applicationpdf": "PDF",
    "fileUpload.imageall": "Images",
    "fileUpload.remove": "Supprimer",
    "fileUpload.title": "Kit média",

    // Traductions manquantes pour le tableau de bord fournisseur
    "supplier.dashboard.title": "Tableau de bord fournisseur",
    "supplier.dashboard.overview": "Vue d'ensemble de votre activité",
    "supplier.dashboard.totalProducts": "Produits totaux",
    "supplier.dashboard.monthlyRevenue": "Chiffre d'affaires mensuel",
    "supplier.dashboard.customerSatisfaction": "Satisfaction client",
    "supplier.dashboard.viewAllProducts": "Voir tous les produits",
    "supplier.dashboard.viewAnalytics": "Voir les analyses",
    "supplier.dashboard.viewReviews": "Voir les avis",
    "supplier.dashboard.importantAlerts": "Alertes importantes",
    "supplier.dashboard.addProduct": "Ajouter un produit",
    "supplier.dashboard.addProductDesc": "Créer une nouvelle fiche produit",
    "supplier.dashboard.messages": "Messages",
    "supplier.dashboard.threeNewMessages": "3 nouveaux messages",
    "supplier.dashboard.documents": "Documents",
    "supplier.dashboard.manageDocuments": "Gérer vos documents",
    "supplier.dashboard.salesPerformance": "Performance des ventes",
    "supplier.dashboard.revenue": "Chiffre d'affaires",
    "supplier.dashboard.last30Days": "30 derniers jours",
    "supplier.dashboard.month": "Mois",
    "supplier.dashboard.year": "Année",
    "supplier.dashboard.salesChart": "Graphique des ventes",
    "supplier.dashboard.dataWillDisplay": "Les données seront affichées ici",

    // Traductions pour la gestion des produits
    "supplier.products.title": "Gestion des produits",
    "supplier.products.subtitle": "Gérez votre catalogue de produits",
    "supplier.products.manage": "Gérez votre catalogue",
    "supplier.products.search": "Rechercher un produit...",
    "supplier.products.add": "Ajouter un produit",
    "supplier.products.addProduct": "Ajouter un produit",
    "supplier.products.resetDefault": "Restaurer par défaut",
    "supplier.products.allCategories": "Toutes les catégories",
    "supplier.products.autosave": "Sauvegarde automatique activée",
    "supplier.products.synced": "Synchronisé avec l'onglet Découvrir",
    "supplier.products.back": "Retour au tableau de bord",
    "supplier.products.totalProducts": "Total Produits",
    "supplier.products.stats.totalProducts": "Total Produits",
    "supplier.products.stats.views": "Vues ce mois",
    "supplier.products.stats.rating": "Note moyenne",
    "supplier.products.stats.inStock": "En stock",
    "supplier.products.inStock": "En stock",
    "supplier.products.name": "Nom",
    "supplier.products.category": "Catégorie",
    "supplier.products.price": "Prix d'usine",
    "supplier.products.actions": "Actions",
    "supplier.products.edit": "Modifier",
    "supplier.products.delete": "Supprimer",
    "supplier.products.deleteConfirm": "Êtes-vous sûr de vouloir supprimer ce produit ?",
    "supplier.products.deleteSuccess": "Produit supprimé avec succès",
    "supplier.products.confirm.reset": "Êtes-vous sûr de vouloir restaurer les produits par défaut ? Tous vos produits ajoutés seront perdus.",
    "supplier.products.success.added": "Produit ajouté avec succès",
    "supplier.products.success.updated": "Produit mis à jour avec succès",
    "supplier.products.success.deleted": "Produit supprimé avec succès",
    "supplier.products.success.reset": "Liste des produits restaurée par défaut",
    "supplier.products.resetSuccess": "Liste des produits restaurée par défaut",
    "supplier.products.addSuccess": "Produit ajouté avec succès",
    "supplier.products.updateSuccess": "Produit mis à jour avec succès",
    "supplier.products.error.save": "Erreur lors de la sauvegarde",
    "supplier.products.noProducts": "Aucun produit trouvé",
    "supplier.products.addFirstProduct": "Ajoutez votre premier produit pour commencer",

    // Traductions pour la gestion des clients
    "supplier.customers.title": "Mes Clients",
    "supplier.customers.subtitle": "Gérez vos relations clients et suivez leur activité",
    "supplier.customers.back": "Retour au tableau de bord",
    "supplier.customers.searchPlaceholder": "Rechercher par nom, email ou entreprise...",
    "supplier.customers.allStatuses": "Tous les statuts",
    "supplier.customers.active": "Actif",
    "supplier.customers.inactive": "Inactif",
    "supplier.customers.totalCustomers": "Total clients",
    "supplier.customers.activeCustomers": "Clients actifs",
    "supplier.customers.newCustomers": "Nouveaux clients",
    "supplier.customers.revenue": "Chiffre d'affaires",
    "supplier.customers.name": "Nom",
    "supplier.customers.email": "Email",
    "supplier.customers.company": "Entreprise",
    "supplier.customers.location": "Localisation",
    "supplier.customers.joinDate": "Client depuis",
    "supplier.customers.totalOrders": "Total commandes",
    "supplier.customers.totalSpent": "Total dépensé",
    "supplier.customers.lastOrder": "Dernière commande",
    "supplier.customers.status": "Statut",
    "supplier.customers.actions": "Actions",
    "supplier.customers.view": "Voir",
    "supplier.customers.message": "Message",
    "supplier.customers.loading": "Chargement...",
    "supplier.customers.error": "Erreur lors du chargement des clients",

    // Traductions pour les messages
    "supplier.messages.title": "Messages",
    "supplier.messages.subtitle": "Communiquez avec vos clients",
    "supplier.messages.back": "Retour au tableau de bord",
    "supplier.messages.searchPlaceholder": "Rechercher un message...",
    "supplier.messages.allTypes": "Tous les types",
    "supplier.messages.inquiry": "Demande",
    "supplier.messages.order": "Commande",
    "supplier.messages.support": "Support",
    "supplier.messages.totalMessages": "Total Messages",
    "supplier.messages.unreadMessages": "Messages non lus",
    "supplier.messages.respondedToday": "Répondus aujourd'hui",
    "supplier.messages.from": "De",
    "supplier.messages.subject": "Sujet",
    "supplier.messages.type": "Type",
    "supplier.messages.date": "Date",
    "supplier.messages.reply": "Répondre",
    "supplier.messages.loading": "Chargement...",
    "supplier.messages.error": "Erreur lors du chargement des messages",

    // Traductions pour les documents
    "supplier.documents.title": "Documents",
    "supplier.documents.subtitle": "Gérez vos documents et fichiers",
    "supplier.documents.back": "Retour au tableau de bord",
    "supplier.documents.searchPlaceholder": "Rechercher un document...",
    "supplier.documents.allTypes": "Tous les types",
    "supplier.documents.contract": "Contrat",
    "supplier.documents.invoice": "Facture",
    "supplier.documents.certificate": "Certificat",
    "supplier.documents.manual": "Manuel",
    "supplier.documents.other": "Autre",
    "supplier.documents.allStatuses": "Tous les statuts",
    "supplier.documents.approved": "Approuvé",
    "supplier.documents.pending": "En attente",
    "supplier.documents.rejected": "Rejeté",
    "supplier.documents.uploadDocument": "Télécharger un document",
    "supplier.documents.totalDocuments": "Total Documents",
    "supplier.documents.approvedDocuments": "Documents approuvés",
    "supplier.documents.pendingApproval": "En attente d'approbation",
    "supplier.documents.downloads": "Téléchargements",
    "supplier.documents.document": "Document",
    "supplier.documents.type": "Type",
    "supplier.documents.size": "Taille",
    "supplier.documents.uploadDate": "Date d'upload",
    "supplier.documents.downloadCount": "Téléchargements",
    "supplier.documents.status": "Statut",
    "supplier.documents.actions": "Actions",
    "supplier.documents.preview": "Prévisualiser",
    "supplier.documents.download": "Télécharger",
    "supplier.documents.delete": "Supprimer",
    "supplier.documents.confirm.delete": "Êtes-vous sûr de vouloir supprimer ce document ?",
    "supplier.documents.loading": "Chargement...",
    "supplier.documents.error": "Erreur lors du chargement des documents",

    // Traductions pour les avis clients
    "supplier.reviews.title": "Avis Clients",
    "supplier.reviews.subtitle": "Consultez et répondez aux avis de vos clients",
    "supplier.reviews.back": "Retour au tableau de bord",
    "supplier.reviews.searchPlaceholder": "Rechercher dans les avis...",
    "supplier.reviews.allRatings": "Toutes les notes",
    "supplier.reviews.5stars": "5 étoiles",
    "supplier.reviews.4stars": "4 étoiles",
    "supplier.reviews.3stars": "3 étoiles",
    "supplier.reviews.2stars": "2 étoiles",
    "supplier.reviews.1star": "1 étoile",
    "supplier.reviews.verified": "Vérifiés",
    "supplier.reviews.unverified": "Non vérifiés",
    "supplier.reviews.averageRating": "Note moyenne",
    "supplier.reviews.totalReviews": "Total Avis",
    "supplier.reviews.positiveReviews": "Avis positifs",
    "supplier.reviews.responseRate": "Taux de réponse",
    "supplier.reviews.customer": "Client",
    "supplier.reviews.product": "Produit",
    "supplier.reviews.rating": "Note",
    "supplier.reviews.comment": "Commentaire",
    "supplier.reviews.date": "Date",
    "supplier.reviews.respond": "Répondre",
    "supplier.reviews.response": "Réponse du fournisseur",
    "supplier.reviews.verified.badge": "Vérifié",
    "supplier.reviews.helpful": "trouvent cet avis utile",
    "supplier.reviews.loading": "Chargement...",
    "supplier.reviews.error": "Erreur lors du chargement des avis",

    // Traductions pour les analyses
    "supplier.analytics.title": "Analyses",
    "supplier.analytics.subtitle": "Analysez vos performances",
    "supplier.analytics.back": "Retour au tableau de bord",
    "supplier.analytics.period.1month": "1 mois",
    "supplier.analytics.period.3months": "3 mois",
    "supplier.analytics.period.6months": "6 mois",
    "supplier.analytics.period.1year": "1 an",
    "supplier.analytics.refresh": "Actualiser",
    "supplier.analytics.export": "Exporter",
    "supplier.analytics.revenue": "Chiffre d'affaires",
    "supplier.analytics.orders": "Commandes",
    "supplier.analytics.customers": "Nouveaux clients",
    "supplier.analytics.productViews": "Vues produits",
    "supplier.analytics.salesEvolution": "Évolution des ventes",
    "supplier.analytics.vsLastMonth": "vs mois dernier",
    "supplier.analytics.topProducts": "Produits les plus vendus",
    "supplier.analytics.customerSatisfaction": "Satisfaction client",
    "supplier.analytics.loading": "Chargement des données...",
    "supplier.analytics.error": "Erreur lors du chargement des analyses",

    // Traductions pour les paramètres
    "supplier.settings.title": "Paramètres",
    "supplier.settings.subtitle": "Configurez votre compte et vos préférences",
    "supplier.settings.back": "Retour au tableau de bord",
    "supplier.settings.company": "Entreprise",
    "supplier.settings.profile": "Profil",
    "supplier.settings.notifications": "Notifications",
    "supplier.settings.security": "Sécurité",
    "supplier.settings.billing": "Facturation",
    "supplier.settings.companyInfo": "Informations de l'entreprise",
    "supplier.settings.companyName": "Nom de l'entreprise",
    "supplier.settings.contactEmail": "Email de contact",
    "supplier.settings.phone": "Téléphone",
    "supplier.settings.address": "Adresse",
    "supplier.settings.city": "Ville",
    "supplier.settings.postalCode": "Code postal",
    "supplier.settings.country": "Pays",
    "supplier.settings.website": "Site web",
    "supplier.settings.description": "Description de l'entreprise",
    "supplier.settings.contactInfo": "Informations de contact",
    "supplier.settings.contactName": "Nom du contact",
    "supplier.settings.contactPhone": "Téléphone du contact",
    "supplier.settings.position": "Poste",
    "supplier.settings.emailNotifications": "Notifications par email",
    "supplier.settings.pushNotifications": "Notifications push",
    "supplier.settings.orderNotifications": "Nouvelles commandes",
    "supplier.settings.messageNotifications": "Nouveaux messages",
    "supplier.settings.reviewNotifications": "Nouveaux avis",
    "supplier.settings.marketingNotifications": "Marketing",
    "supplier.settings.twoFactorAuth": "Authentification à deux facteurs",
    "supplier.settings.passwordExpiry": "Expiration du mot de passe",
    "supplier.settings.sessionTimeout": "Délai d'expiration de session",
    "supplier.settings.changePassword": "Changer le mot de passe",
    "supplier.settings.currentPassword": "Mot de passe actuel",
    "supplier.settings.newPassword": "Nouveau mot de passe",
    "supplier.settings.confirmPassword": "Confirmer le mot de passe",
    "supplier.settings.save": "Enregistrer",
    "supplier.settings.saveChanges": "Enregistrer les modifications",
    "supplier.settings.cancel": "Annuler",
    "supplier.settings.loading": "Chargement...",
    "supplier.settings.saved": "Paramètres sauvegardés",
    "supplier.settings.error": "Erreur lors de la sauvegarde",

    // Traductions pour les filtres de recherche
    "search.filter.allCategories": "Toutes les catégories",
    "search.filter.name": "Nom du produit",
    "search.filter.category": "Catégorie",
    "search.filter.moq": "Quantité minimum (MOQ)",
    "search.filter.priceRange": "Fourchette de prix",
    "search.filter.minPrice": "Prix minimum",
    "search.filter.maxPrice": "Prix maximum",
    "search.filter.ce": "Certifié CE",

    // Traductions pour le modal de produit
    "product.modal.addTitle": "Ajouter un produit",
    "product.modal.editTitle": "Modifier le produit",
    "product.modal.productName": "Nom du produit",
    "product.modal.productNamePlaceholder": "Entrez le nom du produit",
    "product.modal.productId": "ID Produit",
    "product.modal.productIdPlaceholder": "Entrez l'ID du produit",
    "product.modal.description": "Description",
    "product.modal.descriptionPlaceholder": "Décrivez votre produit...",
    "product.modal.factoryPrice": "Prix d'usine (CNY)",
    "product.modal.factoryPricePlaceholder": "Entrez le prix d'usine",
    "product.modal.category": "Catégorie",
    "product.modal.selectCategory": "Sélectionnez une catégorie",
    "product.modal.minOrder": "Commande minimum",
    "product.modal.minOrderPlaceholder": "Quantité minimum de commande",
    "product.modal.stockAvailable": "Stock disponible",
    "product.modal.tags": "Tags",
    "product.modal.addTag": "Ajouter un tag...",
    "product.modal.specifications": "Spécifications techniques",
    "product.modal.brand": "Marque",
    "product.modal.brandPlaceholder": "Ex. Apple, Samsung...",
    "product.modal.origin": "Origine",
    "product.modal.originPlaceholder": "Ex. Chine, France...",
    "product.modal.material": "Matériau",
    "product.modal.materialPlaceholder": "Ex. Plastique, Métal...",
    "product.modal.modelNumber": "Numéro de modèle",
    "product.modal.modelNumberPlaceholder": "Ex. iPHB-128",
    "product.modal.images": "Images du produit",
    "product.modal.dropImages": "Déposez vos images ici",
    "product.modal.selectImages": "ou cliquez pour sélectionner des images",
    "product.modal.supportedFormats": "Formats acceptés: JPG, JPEG, PNG, GIF | Taille max: 5MB par image",
    "product.modal.maxImages": "Vous pouvez ajouter jusqu'à 8 images. Formats acceptés: JPG, PNG, GIF. Taille max par image.",
    "product.modal.cancel": "Annuler",
    "product.modal.save": "Sauvegarder",

    // Traductions pour les conteneurs
    "containers": "Conteneurs",
    "containers.title": "Liste des conteneurs",
    "containers.loading": "Chargement des conteneurs...",
    "containers.error": "Erreur de chargement",
    "containers.name": "Nom du conteneur",
    "containers.departure": "Lieu de départ",
    "containers.arrival": "Lieu d'arrivée",
    "containers.estimatedDeparture": "Date de départ estimée",
    "containers.status": "Statut",
    "containers.status.active": "Actif",
    "containers.status.closed": "Clôturé",
    "containers.capacity": "Capacité",
    "containers.usedCapacity": "Capacité utilisée",
    "containers.availableCapacity": "Capacité disponible",
    "containers.totalCapacity": "Capacité totale",
    "containers.closedMessage": "Ce conteneur est clôturé et n'est plus réservable.",
    "containers.almostFullMessage": "Ce conteneur est presque plein, réservez vite !",
    "containers.availableMessage": "Ce conteneur est disponible pour de nouvelles réservations.",

    // Traductions pour la précommande de conteneurs
    "preorder.title": "Précommande d'espace conteneur",
    "preorder.description": "Réservez votre espace dans ce conteneur avant qu'il ne soit complet.",
    "preorder.quantity": "Quantité (CBM)",
    "preorder.button": "Précommander",
    "preorder.confirm": "Confirmer la précommande",
    "preorder.cancel": "Annuler",
    "preorder.success": "Votre précommande a été enregistrée avec succès !",
    "preorder.availableCapacity": "Capacité disponible",
    "preorder.terms": "J'accepte les conditions générales",
    "preorder.termsRequired": "Vous devez accepter les conditions générales",

    // Traductions pour les articles de conteneurs
    "containerItems.title": "Articles du conteneur",
    "containerItems.productId": "ID Produit",
    "containerItems.quantity": "Quantité",
    "containerItems.userId": "Utilisateur",
    "containerItems.loading": "Chargement des articles...",
    "containerItems.error": "Erreur lors du chargement des articles",
    "containerItems.noItems": "Aucun article dans ce conteneur",
    "containerItems.addItem": "Ajouter un article",

    // SupplierProfile Page translations
    "supplier.loadingProfile": "جاري تحميل الملف الشخصي...",
    "supplier.goldSupplier": "مورد ذهبي",
    "supplier.reviews": "مراجعات",
    "supplier.since": "منذ",
    "supplier.contact": "اتصال",
    "supplier.viewProducts": "عرض المنتجات",
    "supplier.overview": "نظرة عامة",
    "supplier.products": "المنتجات",
    "supplier.businessCards": "بطاقات العمل",
    "supplier.certifications": "الشهادات",
    "supplier.gallery": "المعرض",
    "supplier.aboutCompany": "حول الشركة",
    "supplier.specialties": "التخصصات",
    "supplier.performance": "الأداء",
    "supplier.ordersCompleted": "الطلبات المكتملة",
    "supplier.responseTime": "وقت الاستجابة",
    "supplier.onTimeDelivery": "التسليم في الوقت المحدد",
    "supplier.viewAll": "عرض الكل",
    "supplier.myBusinessCards": "بطاقات العمل الخاصة بي",
    "supplier.createBusinessCardsDesc": "أنشئ وخصص بطاقات العمل المهنية الخاصة بك. شاركها بسهولة مع عملائك وشركائك.",
    "supplier.viewBusinessCardsDesc": "اكتشف بطاقات عمل هذا المورد وحملها لجهات الاتصال الخاصة بك.",
    "supplier.businessCardsAvailable": "بطاقات العمل متاحة",
    "supplier.supplierSharesCards": "يشارك هذا المورد بطاقات عمله مع الشركاء.",
    "supplier.certificationsAndStandards": "الشهادات والمعايير",
    "supplier.validCertification": "شهادة صالحة",
    "supplier.companyGallery": "معرض الشركة",
    "supplier.customerReviews": "مراجعات العملاء",
    "supplier.weeksAgo": "منذ {{count}} أسبوع{{count, plural, one {} other {}}}",
    "supplier.sampleReviewText": "مورد ممتاز! جودة منتج لا تشوبها شائبة وتسليم سريع جداً. أنصح بشدة.",
    "supplier.helpful": "مفيد",
    "supplier.reply": "رد",
    "supplier.contactInfo": "معلومات الاتصال",
    "supplier.address": "العنوان",
    "supplier.phone": "الهاتف",
    "supplier.email": "البريد الإلكتروني",
    "supplier.website": "الموقع الإلكتروني",
    "supplier.companyInfo": "معلومات الشركة",
    "supplier.foundedIn": "تأسست في",
    "supplier.employees": "الموظفون",
    "supplier.quickActions": "إجراءات سريعة",
    "supplier.sendMessage": "إرسال رسالة",
    "supplier.requestQuote": "طلب عرض أسعار",
    "supplier.downloadCatalog": "تنزيل الكتالوج",

    // ترجمات عامة
    "units": "وحدات",
    "cbm": "CBM",
    "cancel": "إلغاء",
    "confirm": "تأكيد",
    "close": "إغلاق"
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<UserLanguage>('fr');

  const t = useCallback((key: string, params?: Record<string, any>) => {
    let translation = translations[currentLanguage]?.[key] || translations.fr[key] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        translation = translation.replace(new RegExp(`{{${paramKey}}}`, 'g'), value);
      });
    }
    
    return translation;
  }, [currentLanguage]);

  const changeLanguage = useCallback((language: UserLanguage) => {
    setCurrentLanguage(language);
  }, []);

  return (
    <LanguageContext.Provider value={{ currentLanguage, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};